#!/usr/bin/env bash
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2017-2018 Nathan Chancellor
#
# build-kernel wrapper


# build-kernel wrapper for known trees
function bk() {
    local FOLDER PARAMS

    FOLDER=$(basename "${PWD}")

    case "${FOLDER}:$(git cb)" in
        # Custom ROMs
        "du-op5:o8x-caf"*) PARAMS=( oneplus5_defconfig -c ) ;;
        "gzr-op3:"*) PARAMS=( lineageos_oneplus3_defconfig ) ;;
        "gzr-op5:"*|"aicp-op5:"*) PARAMS=( lineage_oneplus5_defconfig -c ) ;;
        "lineage-nash:lineage-15.1") PARAMS=( lineageos_nash_defconfig -c ) ;;
        "lineage-op6:"*) PARAMS=( enchilada_defconfig ) ;;

        # android-linux-stable
        "angler:"*|"bullhead:"*|"marlin:"*) PARAMS=( "${FOLDER}_defconfig" ) ;;
        "mata:lineage-15.1") PARAMS=( "lineageos_${FOLDER}_defconfig" -c ) ;;
        "msm-3.18:"*|"msm-4.4:"*) PARAMS=( msmcortex-perf_defconfig ) ;;
        "msm-4.9:"*) PARAMS=( sdm845-perf_defconfig ) ;;
        "op3:android-8.1") PARAMS=( omni_oneplus3_defconfig ) ;;
        "op3:lineage-15.1") PARAMS=( lineageos_oneplus3_defconfig ) ;;
        "op3:oneplus/QC8996_O_8.0.0"*) PARAMS=( msm-perf_defconfig ) ;;
        "op5:android-8.1") PARAMS=( omni_oneplus5_defconfig ) ;;
        "op5:lineage-15.1") PARAMS=( lineage_oneplus5_defconfig ) ;;
        "op5:oneplus/QC8998_O_8."*) PARAMS=( msmcortex-perf_defconfig ) ;;
        "op6:android-8.1") PARAMS=( omni_oneplus6_defconfig ) ;;
        "op6:lineage-15.1") PARAMS=( enchilada_defconfig ) ;;
        "op6:oneplus/SDM845_O_8.1") PARAMS=( sdm845-perf_defconfig ) ;;
        "polaris"*) PARAMS=( polaris_user_defconfig ) ;;
        "sagit:sagit-o-oss") PARAMS=( sagit_user_defconfig ) ;;
        "tissot:tissot-o-oss"*) PARAMS=( tissot-perf_defconfig ) ;;
        "wahoo:"*) PARAMS=( wahoo_defconfig -c ) ;;
        "whyred:whyred-o-oss") PARAMS=( whyred-perf_defconfig ) ;;

        # Franco Kernel
        "op3:oreo"|"mido:oreo-treble"|"tissot:oreo"*) PARAMS=( franco_defconfig ) ;;

        # Unknown choice
        *) display_error "Kernel not supported by wrapper!" && return 1 ;;
    esac

    build-kernel -w -d "${PARAMS[@]}" "${@}"
}
