#!/usr/bin/env bash
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2018 Nathan Chancellor
#
# Formatted kernel version display functions for kernel build scripts


# Export version variable
function evv() {
    FILE="${OUT_FOLDER:-out}"/include/generated/compile.h
    export "$(grep "${1}" "${FILE}" | cut -d'"' -f1 | awk '{print $2}')"="$(grep "${1}" "${FILE}" | cut -d'"' -f2)"
}


# Show the version as if looking at "Settings -> About phone" on Android Oreo 8.1
function formatted_kernel_version() {
    evv UTS_VERSION
    evv LINUX_COMPILE_BY
    evv LINUX_COMPILE_HOST
    evv LINUX_COMPILER

    VERSION_STRING=$(cat "${OUT_FOLDER:-out}"/include/config/kernel.release)

    [[ ${2} =~ -p ]] && unset BOLD RST

    case "${1}" in
        # 'cat /proc/version'
        "full")
            echo "${BOLD}Version:${RST}    Linux version ${VERSION_STRING} (${LINUX_COMPILE_BY}@${LINUX_COMPILE_HOST}) (${LINUX_COMPILER}) ${UTS_VERSION}"
            echo ;;
        # Formatted 'uname -rv': https://android.googlesource.com/platform/frameworks/base/+/d32e79feb3b894288dde86c5b03bff241d816371
        "pie")
            echo "${BOLD}Version:${RST}    ${VERSION_STRING}"
            echo "            #${KBUILD_BUILD_NUMBER:-1} ${UTS_VERSION#*PREEMPT }"
            echo ;;
        # Formatted 'cat /proc/version': https://android.googlesource.com/platform/frameworks/base/+/fa89b60167d698bf8976e59ec97e0a14a0433e38
        "oreo"*)
            echo "${BOLD}Version:${RST}    ${VERSION_STRING} (${LINUX_COMPILER})"
            [[ ${1} =~ -small ]] && return
            echo "            ${LINUX_COMPILE_BY}@${LINUX_COMPILE_HOST} #${KBUILD_BUILD_NUMBER:-1}"
            echo "            ${UTS_VERSION#*PREEMPT }"
            echo ;;
        # 'uname -r'
        *)
            echo "${BOLD}Version:${RST}    ${VERSION_STRING}"
            echo ;;
    esac

    if [[ ${2} =~ -p ]]; then
        BOLD="\033[1m"
        RST="\033[0m"
        export BOLD RST
    fi
}
