session_name: main
windows:
- window_name: btop and host
  panes:
  - shell: /usr/bin/fish
    shell_command: btop
  - shell: /usr/bin/fish
- window_name: distrobox
  focus: true
  panes:
  - shell: /usr/bin/fish -c dbxe
