session_name: qemu
windows:
- window_name: distrobox and cbl_vmm
  focus: true
  layout: 61d8,269x53,0,0[269x41,0,0,57,269x11,0,42{134x11,0,42,58,134x11,135,42,59}]
  start_directory: '~'
  panes:
  - shell: dbxe
    shell_command:
    - cmd: ssh_vm
      enter: false
  - shell: dbxe
    shell_command:
    - cmd: cbl_test_kvm
      enter: false
    focus: true
  - shell: dbxe
