session_name: main
before_script: ./start-distrobox.fish
windows:
- window_name: btop and distrobox
  panes:
  - btop --utf-force
  - shell: dbxe
    shell_command:
    - cmd: cbl_bld_all
      enter: false
- window_name: host and distrobox
  layout: 775f,269x53,0,0[269x41,0,0,3,269x11,0,42,4]
  focus: true
  panes:
  - shell_command:
    - cmd: cbl_qualify_next
      enter: false
    focus: true
  - shell: have_dev_kvm_access; and dbxe
    shell_command:
    - cmd: cbl_test_kvm vmm
      enter: false
