session_name: main
windows:
  - window_name: btop
    panes:
      - shell: /usr/bin/fish -c btop
  - window_name: host
    panes:
      - shell: /usr/bin/fish
  - window_name: distrobox
    focus: true
    panes:
      - shell: /usr/bin/fish -c dbxe
