session_name: main
windows:
- window_name: btop and host shell
  panes:
  - shell: /usr/bin/fish -c btop
  - shell: /usr/bin/fish
- window_name: distrobox
  focus: true
  panes:
  - shell: /usr/bin/fish -c dbxe
