[Match]
Distribution=fedora

[Content]
Packages=
        # base
        doas
        systemd-pam

        # cvise
        cvise

        # development
        glibc-devel
        glibc-static
        libfl-devel
        make
        patch
        texinfo-tex

        # email
        cyrus-sasl-plain
        lei
        mutt

        # git
        gh
        git-email

        # kernel / tuxmake
        binutils-arm-linux-gnu
        binutils-mips64-linux-gnu
        binutils-powerpc64-linux-gnu
        binutils-powerpc64le-linux-gnu
        binutils-riscv64-linux-gnu
        binutils-s390x-linux-gnu
        dwarves
        elfutils-libelf-devel
        gcc
        gcc-c++
        gcc-arm-linux-gnu
        gcc-mips64-linux-gnu
        gcc-powerpc64-linux-gnu
        gcc-powerpc64le-linux-gnu
        gcc-riscv64-linux-gnu
        gcc-s390x-linux-gnu
        gmp-devel
        libmpc-devel
        libuuid-devel
        ncurses-devel
        openssl-devel
        openssl-devel-engine
        perl
        time
        uboot-tools

        # LLVM/clang + build-llvm.py
        binutils-devel
        clang
        lld
        llvm
        ninja-build
        perf
        zlib-devel

        # package building
        dnf5
        dpkg-dev
        rpm-build

        # pahole
        elfutils-devel

        # python
        # cvise
        python3-chardet
        # spdxcheck.py
        python3-GitPython
        python3-ply

        # QEMU
        qemu-guest-agent
        qemu-img
        qemu-system-aarch64
        qemu-system-arm
        qemu-system-loongarch64
        qemu-system-mips
        qemu-system-ppc
        qemu-system-riscv
        qemu-system-s390x
        qemu-system-x86

        # website management
        hugo
        iproute

[Output]
ImageId=dev-fedora
