#!/usr/bin/env bash
# Function to upload to del.dog
#
# This can be downloaded and sourced without any of the other scripts in this repo.
#
# $ curl -LSsO https://github.com/nathanchance/scripts/raw/master/env/stubs/deldog
#
# Open the deldog file to make sure it matches this one.
#
# $ source deldog
#
# Usage:
# $ deldog <file>
# $ command |& deldog
function deldog() {
    local binary curl_args _haste_url result

    for binary in curl jq; do
        command -v ${binary} &>/dev/null || {
            echo "ERROR: ${binary} is not installed"
            return 1
        }
    done

    _haste_url=${HASTE_URL:-https://del.dog}
    [[ -n ${DEL_DOG_API_KEY} && ${_haste_url} =~ del ]] && curl_args=(--header "X-api-key: ${DEL_DOG_API_KEY}")
    result=$(curl -sf --data-binary @"${1:--}" "${curl_args[@]}" "${_haste_url}"/documents) || {
        echo "ERROR: failed to post document, ca-certificates might need to be installed"
        return 1
    }
    echo "${_haste_url}/raw/$(jq -r .key <<<"${result}")"
}
# vi: filetype=zsh
