#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
#
# Shebang is purely for syntax highlighting and shellcheck auditing; script must be sourced to be useful
#
# Copyright (C) 2021 Nathan Chancellor
#
# shellcheck disable=SC2034

[[ -z ${MAIN_FOLDER} ]] && MAIN_FOLDER=${HOME}
KERNEL_FOLDER=${MAIN_FOLDER}/kernels
GITHUB_FOLDER=${MAIN_FOLDER}/github
[[ -z ${SCRIPTS_FOLDER} ]] && SCRIPTS_FOLDER=${GITHUB_FOLDER}/scripts
SRC_FOLDER=${MAIN_FOLDER}/src
TMP_FOLDER=${MAIN_FOLDER}/tmp
TC_FOLDER=${MAIN_FOLDER}/toolchains
ANDROID_TC_FOLDER=${TC_FOLDER}/android
GCC_TC_FOLDER=${TC_FOLDER}/gcc
LLVM_TC_FOLDER=${TC_FOLDER}/llvm
USR_FOLDER=${MAIN_FOLDER}/usr

# android-linux-stable folder
ALS=${MAIN_FOLDER}/als

# ClangBuiltLinux folder
CBL=${MAIN_FOLDER}/cbl

# We need this for other scripts
export GCC_TC_FOLDER

# vi: filetype=zsh
