#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Shebang is purely for syntax highlighting and shellcheck auditing; script must be sourced to be useful
#
# Copyright (C) 2021 Nathan Chancellor
#
# Functions used to assist with upstream kernel development

# Apply patch from LKML using b4
function b4a() { (
    command -v b4 &>/dev/null || die "b4 needs to be installed"
    in_kernel_tree

    B4_ARGS=()
    while ((${#})); do
        case ${1} in
            http* | *@*) MSG_ID=${1} ;;
            -P) B4_ARGS+=(-P "${1}") && shift ;;
            am) METHOD=(am) ;;
            ams) METHOD=(ams) ;;
            # The default
            ap | apply) ;;
        esac
        shift
    done
    [[ -z ${MSG_ID} ]] && die "Message ID needs to be passed to script"
    [[ -z ${METHOD[*]} ]] && METHOD=(apply -v)

    b4 am -o - -l "${B4_ARGS[@]}" "${MSG_ID}" | git "${METHOD[@]}" -3
); }

# checkpatch.pl shorthand
function chp() { (
    [[ -x scripts/checkpatch.pl ]] || die "checkpatch.pl does not exist"
    scripts/checkpatch.pl "${@}"
); }

# Grab an thread as an mbox file with b4
function gmbx() { (
    command -v b4 &>/dev/null || die "b4 needs to be installed"

    MSG_ID=${1:?}
    MBOX=$(mktemp --suffix=.mbox)

    set -x

    b4 mbox -n "${MBOX}" "${MSG_ID}" || exit ${?}
    neomutt -f "${MBOX}"
    rm "${MBOX}"
); }

# get_maintainer.pl shorthand
# SC2120: gtm references arguments, but none are ever passed.
# shellcheck disable=SC2120
function gtm() { (
    [[ -x scripts/get_maintainer.pl ]] || die "get_maintainer.pl does not exist"
    scripts/get_maintainer.pl --scm "${@}"
); }

# Check if we are in a kernel tree or not
function in_kernel_tree() {
    [[ -f Makefile ]] || die "You do not appear to be in a kernel tree"
}

# Patch check function
function pch() { (
    in_kernel_tree

    REV=${1}
    [[ -z ${REV} ]] && REV=HEAD~1..HEAD

    for SHA in $(git log --format=%H --no-merges --reverse "${REV}"); do
        TITLE="Commit $(git kf "${SHA}")"
        HEADER=$(for _ in $(seq ${#TITLE}); do printf '-'; done)
        printf "\n%s\n%s\n%s\n\n" "${HEADER}" "${TITLE}" "${HEADER}"
        chp -g "${SHA}"
        # SC2119: Use gtm "$@" if function's $1 should mean script's $1.
        # shellcheck disable=SC2119
        git fp -1 --stdout "${SHA}" | gtm
    done
); }

# Quilt-like patch management function for Linux
function ptchmn() { (
    in_kernel_tree

    REPO=${PWD##*/}
    TARGET_FOLDER=${GITHUB_FOLDER}/patches/${REPO}/$(git cb)
    [[ ! -d ${TARGET_FOLDER} ]] && die "${TARGET_FOLDER} doesn't exist!"

    case "${1:?}" in
        -s | --sync)
            case ${REPO} in
                linux | linux-next | linux-stable-5.4 | linux-stable-5.10 | linux-stable-5.11) ;;
                *) die "${REPO} not supported by ptchmn!" ;;
            esac

            FIRST_HASH=$(git mfc)
            [[ -z ${FIRST_HASH} ]] && die "FIRST_HASH is empty...?"

            rm "${TARGET_FOLDER}"/*

            git fp -o "${TARGET_FOLDER}" --base="${FIRST_HASH}^" "${FIRST_HASH}"^..HEAD

            git -C "${TARGET_FOLDER}" aa

            git -C "${TARGET_FOLDER}" c -m "patches: ${REPO}: $(git cb): Sync as of $(git sh -s --format=%h)"

            git -C "${TARGET_FOLDER}" push
            ;;

        -a | --apply)
            git am "${TARGET_FOLDER}"/*
            ;;
    esac
); }

# Rebase a linux-next branch
function rbln() { (
    in_kernel_tree

    FIRST_HASH=$(git mfc)
    SECOND_HASH=$(git show -s --format=%H "$(git cb)")
    git rh origin/master
    git cherry-pick --gpg-sign "${FIRST_HASH}^..${SECOND_HASH}"
); }

# Rebase Raspberry Pi kernel
function rbpi() { (
    PI_SRC=${CBL_BLD:?}/rpi

    set -x

    cd "${PI_SRC}" || exit ${?}
    git ru || exit ${?}
    git rh origin/master
    PATCHES_FOLDER=${GITHUB_FOLDER}/patches/rpi-next
    FIXES=${PATCHES_FOLDER}/fixes.series
    [[ -f ${FIXES} ]] && { git am "${FIXES}" || exit ${?}; }
    git rv --no-edit e8805271b82793e6d1f3de786c2278e4d622bdb6 || exit ${?}
    cat <<'EOF' | git ams || exit ${?}
From a5cb5f5c9816535eb82be6b47fc7fdb6ec37122d Mon Sep 17 00:00:00 2001
From: Nathan Chancellor <nathan@kernel.org>
Date: Wed, 24 Feb 2021 11:23:50 -0700
Subject: [PATCH] swiotlb: Apply Nicolas Saenz Julienne's fix

Link: https://lore.kernel.org/r/70edceb03e4bf283072397f9563dfc4162aec92a.camel@suse.de/
Signed-off-by: Nathan Chancellor <nathan@kernel.org>
---
 kernel/dma/swiotlb.c | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/kernel/dma/swiotlb.c b/kernel/dma/swiotlb.c
index 369e4c3a0f2b..c10e855a03bc 100644
--- a/kernel/dma/swiotlb.c
+++ b/kernel/dma/swiotlb.c
@@ -534,7 +534,7 @@ static int find_slots(struct device *dev, phys_addr_t orig_addr,
 	unsigned long boundary_mask = dma_get_seg_boundary(dev);
 	dma_addr_t tbl_dma_addr =
 		phys_to_dma_unencrypted(dev, io_tlb_start) & boundary_mask;
-	unsigned int max_slots = get_max_slots(boundary_mask);
+	unsigned long max_slots = get_max_slots(boundary_mask);
 	unsigned int iotlb_align_mask =
 		dma_get_min_align_mask(dev) & ~(IO_TLB_SIZE - 1);
 	unsigned int nslots = nr_slots(alloc_size), stride;
-- 
2.30.1

EOF
    ../pi-scripts/build.sh ARCH=arm || exit ${?}
    ../pi-scripts/build.sh ARCH=arm64 || exit ${?}
    if ! git pll --no-edit mainline master; then
        rg "<<<<<<< HEAD" && exit ${?}
        ../pi-scripts/build.sh ARCH=arm || exit ${?}
        ../pi-scripts/build.sh ARCH=arm64 || exit ${?}
        git aa
        git c || exit ${?}
    fi
    if ! git pll --no-edit sami clang-cfi; then
        rg "<<<<<<< HEAD" && exit ${?}
        ../pi-scripts/build.sh ARCH=arm || exit ${?}
        ../pi-scripts/build.sh ARCH=arm64 || exit ${?}
        git aa
        git c --no-edit || exit ${?}
    fi
    ../pi-scripts/build.sh ARCH=arm || exit ${?}
    ../pi-scripts/build.sh ARCH=arm64 || exit ${?}
); }

# Update wsl2-kernel to latest -next
function rbwk() { (
    case ${LOCATION} in
        workstation) WSL2_KERNEL=${HOME}/cbl/build/wsl2 ;;
        wsl) WSL2_KERNEL=${HOME}/src/wsl2-kernel ;;
        *) die "rbwk() is not supported by ${LOCATION}" ;;
    esac

    set -x
    cd "${WSL2_KERNEL}" || exit ${?}
    git ru || exit ${?}
    for BRANCH in clearlinux-patchset microsoft-patchset; do
        git ch "${BRANCH}" || exit ${?}
        git rb -i next/master || exit ${?}
    done
    git ch next || exit ${?}
    git rh next/master
    if ! git pll --no-edit mainline master; then
        rg "<<<<<<< HEAD" && exit ${?}
        git aa
        git c || exit ${?}
    fi
    if ! git pll --no-edit sami clang-cfi; then
        rg "<<<<<<< HEAD" && exit ${?}
        git aa
        git c || exit ${?}
    fi
    git ml --no-edit clearlinux-patchset microsoft-patchset || exit ${?}
    git cp "$(git lo --merges -1 --format=%H origin/HEAD)".."$(git sh -s --format=%H origin/HEAD)"
); }
# vi: filetype=zsh
