#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
#
# Copyright (C) 2021 Nathan Chancellor
#
# Shebang is purely for syntax highlighting and shellcheck auditing; script must be sourced to be useful

function TRAPTERM() {
    echo
    display_error "Program killed!"
    return 1
}

function TRAPINT() {
    echo
    display_error "Manually aborted!"
    return 1
}
# vi: filetype=zsh
