#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2021 Nathan Chancellor
#
# Shebang is purely for syntax highlighting and shellcheck auditing; script must be sourced to be useful

# Make sure that zfunctions folder exists and set variable for other functions
function setup_zfunctions() {
    ZFUNCTIONS=${HOME}/.zfunctions
    mkdir -p "${ZFUNCTIONS}"
}

# Install Pure prompt
function pure_prompt() { (
    setup_zfunctions
    PURE=${ZFUNCTIONS}/pure
    [[ -d ${PURE} ]] || git clone https://github.com/sindresorhus/pure "${PURE}"
    ln -fs "${PURE}"/pure.zsh "${ZFUNCTIONS}"/prompt_pure_setup
    ln -fs "${PURE}"/async.zsh "${ZFUNCTIONS}"/async
); }

# Install zsh-syntax-highlighting
function zsh_syntax_highlighting() { (
    setup_zfunctions
    ZSH_SH=${ZFUNCTIONS}/zsh-syntax-highlighting
    [[ -d ${ZSH_SH} ]] || git clone https://github.com/zsh-users/zsh-syntax-highlighting "${ZSH_SH}"
    git -C "${ZSH_SH}" pull
); }

# Creates .zshrc
function create_zshrc() { (
    {
        echo "[[ -f ${GITHUB_FOLDER:=${HOME}/github}/scripts/env/common ]] && source \"${GITHUB_FOLDER}/scripts/env/common\""
        echo "type shell_setup &>/dev/null && shell_setup"
    } >"${HOME}"/.zshrc
); }

# Completely setup zsh environment
function setup_zsh_env() { (
    pure_prompt
    zsh_syntax_highlighting
    create_zshrc
); }
# vi: filetype=zsh
