#!/usr/bin/env bash
# shellcheck disable=SC2076
#
# Pull in linux-stable updates to the android-linux-stable trees
#
# Copyright (C) 2018 Nathan Chancellor
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>


source common
ALS_HOME=${HOME}/kernels/als
ALS_PATCHES=${SCRIPTS_FOLDER}/als-patches




# 3.18 kernels
if [[ "$*" =~ "3.18" ]]; then
    # Pixel (XL)
    cd "${ALS_HOME}/marlin" || die "Marlin folder does not exist, please clone!"
    git f origin
    git rh origin/"$(git rev-parse --abbrev-ref HEAD)"

    merge-stable

    git push




    # msm-3.18 tree
    cd "${ALS_HOME}/msm-3.18" || die "msm-3.18 folder does not exist, please clone!"
    git f origin
    git rh origin/"$(git rev-parse --abbrev-ref HEAD)"

    merge-stable

    git push




    # OnePlus 3
    cd "${ALS_HOME}/op3" || die "OnePlus 3 folder does not exist, please clone!"
    git f origin
    git ch oneplus/QC8996_O_8.0.0
    git f upstream || die "upstream remote does not exist!"
    git ml --no-edit upstream/oneplus/QC8996_O_8.0.0 || die "Merge conflicts detected, please resolve then continue!"
    git rh origin/"$(git rev-parse --abbrev-ref HEAD)"

    merge-stable

    git push
    git ch oneplus/QC8996_O_8.0.0_Beta
    git ml --no-edit upstream/oneplus/QC8996_O_8.0.0_Beta || die "Merge conflicts detected, please resolve then continue!"
    git rh origin/"$(git rev-parse --abbrev-ref HEAD)"

    merge-stable

    git push
    git ch lineage-15.1
    git rh origin/"$(git rev-parse --abbrev-ref HEAD)"
    git f LineageOS || die "LineageOS remote does not exist!"
    git ml --no-edit LineageOS/lineage-15.1 || die "Merge conflicts detected, please resolve then continue!"

    merge-stable

    git push
    git ch android-8.1
    git rh origin/"$(git rev-parse --abbrev-ref HEAD)"
    git f omni || die "omni remote does not exist!"
    git ml --no-edit omni/android-8.1 || die "Merge conflicts detected, please resolve then continue!"

    merge-stable

    git push




    # Xiaomi Mi A1 tree
    cd "${ALS_HOME}/tissot" || die "Mi A1 folder does not exist, please clone!"
    git f origin
    git rh origin/"$(git rev-parse --abbrev-ref HEAD)"
    git f upstream || die "upstream remote does not exist!"
    git ml --no-edit upstream/tissot-o-oss || die "Merge conflicts detected, please resolve then continue!"

    merge-stable

    git push
fi








# 4.4 kernels
if [[ "$*" =~ "4.4" ]]; then
    # Essential Phone
    cd "${ALS_HOME}/mata" || die "Mata folder does not exist, please clone!"
    git f origin
    git rh origin/"$(git rev-parse --abbrev-ref HEAD)"
    git f LineageOS || die "LineageOS remote does not exist!"
    git ml --no-edit LineageOS/lineage-15.1 || die "Merge conflicts detected, please resolve then continue!"

    merge-stable

    git push




    # Moto Z2 (Force)
    cd "${ALS_HOME}/nash" || die "Nash folder does not exist, please clone!"
    git ch lineage-15.1
    git f origin
    git rh origin/"$(git rev-parse --abbrev-ref HEAD)"
    git f LineageOS || die "LineageOS remote does not exist!"
    git ml --no-edit LineageOS/lineage-15.1 || die "Merge conflicts detected, please resolve then continue!"

    merge-stable

    git push
    git ch oreo-8.0.0-release-nash
    git rh origin/"$(git rev-parse --abbrev-ref HEAD)"
    git f upstream || die "upstream remote does not exist!"
    git ml --no-edit upstream/oreo-8.0.0-release-nash || die "Merge conflicts detected, please resolve then continue!"

    merge-stable

    git push
    




    # msm-4.4
    cd "${ALS_HOME}/msm-4.4" || die "msm-4.4 folder does not exist, please clone!"
    git f origin
    git rh origin/"$(git rev-parse --abbrev-ref HEAD)"

    merge-stable

    git push




    # OnePlus 5
    cd "${ALS_HOME}/op5" || die "OnePlus 5 folder does not exist, please clone!"
    git ch oneplus/QC8998_O_8.0
    git f origin
    git rh origin/"$(git rev-parse --abbrev-ref HEAD)"
    git f upstream || die "upstream remote does not exist!"
    git ml --no-edit upstream/oneplus/QC8998_O_8.0 || die "Merge conflicts detected, please resolve then continue!"

    merge-stable

    git push
    git ch oneplus/QC8998_O_8.1
    git rh origin/"$(git rev-parse --abbrev-ref HEAD)"
    git ml --no-edit upstream/oneplus/QC8998_O_8.1 || die "Merge conflicts detected, please resolve then continue!"

    merge-stable

    git push
    git ch lineage-15.1
    git rh origin/"$(git rev-parse --abbrev-ref HEAD)"
    git f LineageOS || die "LineageOS remote does not exist!"
    git ml --no-edit LineageOS/lineage-15.1 || die "Merge conflicts detected, please resolve then continue!"

    merge-stable

    git push
    git ch android-8.1
    git rh origin/"$(git rev-parse --abbrev-ref HEAD)"
    git f omni || die "omni remote does not exist!"
    git ml --no-edit omni/android-8.1 || die "Merge conflicts detected, please resolve then continue!"

    merge-stable

    git push




    # Pixel 2 (XL)
    cd "${ALS_HOME}/wahoo" || die "Wahoo folder does not exist, please clone!"
    git f origin
    git rh origin/"$(git rev-parse --abbrev-ref HEAD)"

    merge-stable

    git push




    # Xiaomi Mi 6 and Xiaomi Mi Mix 2
    cd "${ALS_HOME}/sagit" || die "Sagit folder does not exist, please clone!"
    git ch sagit-o-oss
    git f origin
    git rh origin/"$(git rev-parse --abbrev-ref HEAD)"
    git f upstream || die "upstream remote does not exist!"
    git ml --no-edit upstream/sagit-o-oss || die "Merge conflicts detected, please resolve then continue!"

    merge-stable

    git push
    git ch android-8.1
    git rh origin/"$(git rev-parse --abbrev-ref HEAD)"
    git f omni || die "omni remote does not exist!"
    git ml --no-edit omni/android-8.1 || die "Merge conflicts detected, please resolve then continue!"

    merge-stable

    git push
fi
