#!/usr/bin/env bash
#
# Clang compilation script
#
# Copyright (C) 2018 Nathan Chancellor
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>


###############
#             #
#  VARIABLES  #
#             #
###############

# Folder that will house the source and build files
MAIN_FOLDER=${HOME}/toolchains/clang

# Folder that will hold the main LLVM source
LLVM_FOLDER=${MAIN_FOLDER}/llvm

# Folder that will hold all of the build files and compiled code
BUILD_FOLDER=${MAIN_FOLDER}/build

# Start tracking time
START=$(date +"%s")


###############
#             #
#  FUNCTIONS  #
#             #
###############

function parse_parameters() {
    PARAMS="$*"

    while [[ $# -ge 1 ]]; do
        case ${1} in
            "-b"|"--build-only")
                BUILD_ONLY=true ;;

            "-t"|"--telegram")
                TG=true
                TG_MSG_FILE=/tmp/tg-msg.2 ;;

            "-v"|"--version")
                shift && enforce_value "$@"
                VERSION=${1} ;;

            *) die "Invalid parameter specified!" ;;
        esac

        shift
    done

    if [[ ${TG} ]]; then
        {
            echo "\`\`\`"
            echo "Currently executing..."
            echo
            echo "$(basename "${0}") ${PARAMS}"
            echo "\`\`\`"
        } > ${TG_MSG_FILE}
        notify "$(cat ${TG_MSG_FILE})"
    fi

    # Clang 7.x is compiled by default
    [[ -z ${VERSION} ]] && VERSION=7

    # Folder that will hold the final compiled toolchain
    INSTALL_FOLDER=/opt/clang-${VERSION}.x
}

# Syncs requested  projects
function sync() {
    FOLDER=${1}

    if [[ ${FOLDER} =~ "binutils" ]]; then
        URL=http://sourceware.org/git/binutils-gdb.git
        BRANCH=binutils-2_30-branch
    elif [[ ${FOLDER} =~ "llvm-svn" ]]; then
        URL=http://llvm.org/svn/llvm-project/llvm/trunk
    else
        URL=https://git.llvm.org/git/$(basename "${FOLDER}")
        case ${VERSION} in
            "7") BRANCH=master ;;
            *) BRANCH="release_${VERSION}0" ;;
        esac
    fi

    if [[ ! -d ${FOLDER} ]]; then
        case ${FOLDER} in
            "llvm-svn") svn co "${URL}" "${FOLDER}" ;;
            *) git clone "${URL}" -b "${BRANCH}" "${FOLDER}" ;;
        esac
    else
        (
            cd "${FOLDER}" || die "Error moving into ${FOLDER}"
            case ${FOLDER} in
                "llvm-svn")
                    svn update ;;
                *)
                    git clean -fxdq
                    git checkout ${BRANCH}
                    git fetch origin
                    if ! git rebase origin/${BRANCH}; then
                        die "Error updating $(basename "${FOLDER}")!"
                    fi ;;
            esac
        )
    fi
}

# Syncs all necessary projects
function sync_all() {
    header "Syncing projects"

    mkdir -p "${MAIN_FOLDER}"
    cd "${MAIN_FOLDER}" || die "Error creating ${MAIN_FOLDER}!"

    sync llvm
    sync llvm-svn

    mkdir -p "${LLVM_FOLDER}/tools"
    cd "${LLVM_FOLDER}/tools" || die "Error creating tools folder!"

    sync binutils
    sync clang
    sync lld
    sync polly

    mkdir -p "${LLVM_FOLDER}/projects"
    cd "${LLVM_FOLDER}/projects" || die "Error creating projects folder!"

    sync compiler-rt
    sync libcxx
    sync libcxxabi
    sync libunwind
    sync openmp
}

# Removes any previous build files
function cleanup() {
    rm -rf "${BUILD_FOLDER}"
    mkdir -p "${BUILD_FOLDER}"
    cd "${BUILD_FOLDER}" || die "Error creating build folder!"
}

# Build the toolchain
function build() {
    header "Building Clang"

    [[ ${TG} ]] && notify "\`Beginning build of Clang ${VERSION}...\`"

    cmake -DLINK_POLLY_INTO_TOOLS=ON \
          -DCMAKE_CXX_FLAGS="-O3 -Wno-macro-redefined -pipe -pthread -fopenmp -g0 -march=native -mtune=native" \
          -DCMAKE_C_FLAGS="-O3 -Wno-macro-redefined -pipe -pthread -fopenmp -g0 -march=native -mtune=native" \
          -DLLVM_ENABLE_PIC=ON \
          -DCMAKE_INSTALL_PREFIX=${INSTALL_FOLDER} \
          -DLLVM_PARALLEL_COMPILE_JOBS="${THREADS}" \
          -DLLVM_PARALLEL_LINK_JOBS="${THREADS}" \
          -DLLVM_ENABLE_THREADS=ON \
          -DLLVM_ENABLE_WARNINGS=OFF \
          -DLLVM_ENABLE_WERROR=OFF \
          -DLLVM_INCLUDE_EXAMPLES=OFF \
          -DLLVM_INCLUDE_TESTS=OFF \
          -DLLVM_BINUTILS_INCDIR="${LLVM_FOLDER}/tools/binutils/include" \
          -DLLVM_TARGETS_TO_BUILD="X86;ARM;AArch64;NVPTX" \
          -DCMAKE_BUILD_TYPE=MinSizeRel \
          -DLLVM_OPTIMIZED_TABLEGEN=ON \
          -DPOLLY_ENABLE_GPGPU_CODEGEN=ON \
          -DLLVM_CCACHE_BUILD=ON \
          -DLLVM_USE_LINKER=gold \
          -DCLANG_VENDOR="Flash " \
          -DLLVM_VERSION_PATCH="$(cd "${MAIN_FOLDER}/llvm-svn" || die "SVN folder doesn't exist";
                                  svn info -r HEAD --show-item revision)" \
          -DLLVM_VERSION_SUFFIX="" \
          "${LLVM_FOLDER}"

    if ! time cmake --build . -- "${JOBS_FLAG}"; then
        header "ERROR BUILDING!"
        die "Time elapsed: $(format_time "${START}" "$(date +"%s")")"
    fi
}

# Install the toolchain
function install() {
    header "Installing Clang"

    rm -rf "${INSTALL_FOLDER}-old"
    mv "${INSTALL_FOLDER}" "${INSTALL_FOLDER}-old"
    if ! cmake --build . --target install -- "${JOBS_FLAG}"; then
        header "ERROR INSTALLING!"
        if [[ ${TG} ]]; then
            {
                echo "\`\`\`"
                echo "Error while building Clang ${VERSION}!"
                echo
                echo "Time elapsed: $(format_time "${START}" "$(date +"%s")")"
                echo "\`\`\`"
            } > "${TG_MSG_FILE}"
            notify "$(cat ${TG_MSG_FILE})"
        fi
        die "Time elapsed: $(format_time "${START}" "$(date +"%s")")"
    fi

    header "SUCCESS!" "${GRN}"
    TIME_STRING="$(format_time "${START}" "$(date +"%s")")"
    echo "${GRN}Successfully built and installed Clang toolchain to ${INSTALL_FOLDER}!${GRN}"
    echo "${GRN}Time elapsed: ${TIME_STRING,,}${RST}\n"
    if [[ ${TG} ]]; then
        {
            echo "\`\`\`"
            echo "Clang ${VERSION} build was successful!"
            echo
            echo "Time elapsed: ${TIME_STRING,,}"
            echo "\`\`\`"
        } > "${TG_MSG_FILE}"
        notify "$(cat ${TG_MSG_FILE})"
    fi
}

source common
parse_parameters "$@"
sync_all
cleanup
build
[[ ! ${BUILD_ONLY} ]] && install
