#!/usr/bin/env bash
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2018 Nathan Chancellor

build-clang -t

# Flash Kernel OP5 3.x
flash-kernel -d op5 -b 8.x-unified -m tmp -io -t
for i in $(seq 0 8); do
    flash-kernel -d op5 -b 8.x-unified -m tmp -io
done

# Flash Kernel OP5 4.x
flash-kernel -d op5 -b 8.1.0-unified -m tmp -io -t
for i in $(seq 0 8); do
    flash-kernel -d op5 -b 8.1.0-unified -m tmp -io
done

# Flash Kernel Pixel 2 2.x
flash-kernel -d walleye -b oreo-m2 -m tmp -t
for i in $(seq 0 8); do
    flash-kernel -d walleye -b oreo-m2 -m tmp
done

# Flash Kernel Pixel 2 XL 2.x
flash-kernel -d taimen -b oreo-m2 -m tmp -t
for i in $(seq 0 8); do
    flash-kernel -d taimen -b oreo-m2 -m tmp
done

# Flash Kernel OnePlus 5 staging
flash-kernel -d op5 -io -t
for i in $(seq 0 8); do
    flash-kernel -d op5 -io
done

# Flash Kernel Pixel 2 XL staging
flash-kernel -b staging -io -t
for i in $(seq 0 8); do
    flash-kernel -b staging -io
done
