#!/usr/bin/env bash
# shellcheck disable=SC2034,SC1090
#
# Helper functions
#
# Copyright (C) 2016-2018 Nathan Chancellor
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>


###############
#             #
#  VARIABLES  #
#             #
###############

# What OS are we on?
OS=$(UNAME=$(uname); echo "${UNAME,,}")
# GNU readlink is needed for SCRIPTS_FOLDER
if [[ ${OS} = "darwin" ]]; then
    alias readlink=greadlink
fi

# Location of "scripts" folder
SCRIPTS_FOLDER=$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)
BIN_FOLDER=${SCRIPTS_FOLDER}/bin

# Common locations amongst scripts
KERNEL_FOLDER=${HOME}/kernels
MISC_FOLDER=${HOME}/misc
REPO_FOLDER=${HOME}/repos
ROM_FOLDER=${HOME}/roms
TC_FOLDER=${HOME}/toolchains
WEB_FOLDER=${HOME}/web

# Colors
BLINK_RED="\033[05;31m"
BLUE="\033[01;34m"
BOLD="\033[1m"
GRN="\033[01;32m"
RED="\033[01;31m"
RST="\033[0m"
YLW="\033[01;33m"

# Number of make threads
if [[ ${OS} = "darwin" ]]; then
    THREADS=$(sysctl hw.ncpu | cut -d " " -f 2)
else
    THREADS=$(nproc --all)
fi
JOBS_FLAG="-j${THREADS}"

###############
#             #
#  FUNCTIONS  #
#             #
###############

# Alias for echo to print escape codes
function echo() {
    command echo -e "$@"
}

# Prints a formatted header to point out what is being done to the user
function header() {
    if [[ -n ${2} ]]; then
        COLOR=${2}
    else
        COLOR=${RED}
    fi
    echo "${COLOR}"
    echo "====$(for i in $(seq ${#1}); do echo "=\c"; done)===="
    echo "==  ${1}  =="
    echo "====$(for i in $(seq ${#1}); do echo "=\c"; done)===="
    echo "${RST}"
}

# Formats the time
function format_time() {
    MINS=$(((${2} - ${1}) / 60))
    SECS=$(((${2} - ${1}) % 60))
    if [[ ${MINS} -ge 60 ]]; then
        HOURS=$((MINS / 60))
        MINS=$((MINS % 60))
    fi

    if [[ ${HOURS} -eq 1 ]]; then
        TIME_STRING+="1 HOUR, "
    elif [[ ${HOURS} -ge 2 ]]; then
        TIME_STRING+="${HOURS} HOURS, "
    fi

    if [[ ${MINS} -eq 1 ]]; then
        TIME_STRING+="1 MINUTE"
    else
        TIME_STRING+="${MINS} MINUTES"
    fi

    if [[ ${SECS} -eq 1 && -n ${HOURS} ]]; then
        TIME_STRING+=", AND 1 SECOND"
    elif [[ ${SECS} -eq 1 && -z ${HOURS} ]]; then
        TIME_STRING+=" AND 1 SECOND"
    elif [[ ${SECS} -ne 1 && -n ${HOURS} ]]; then
        TIME_STRING+=", AND ${SECS} SECONDS"
    elif [[ ${SECS} -ne 1 && -z ${HOURS} ]]; then
        TIME_STRING+=" AND ${SECS} SECONDS"
    fi

    echo "${TIME_STRING}"
}

# Prints an error in bold red
function display_error() {
    echo
    echo "${RED}${1}${RST}"
    if [[ -z ${2} ]]; then
        echo
    fi
}

# Prints an error in bold red and exits the script
function die() {
    if [[ ${TG} ]]; then
        # Info must be resourced so public chats don't get notified
        load_botinfo
        {
            echo "\`\`\`"
            echo "An error was detected while running the following command:"
            echo
            echo "$(basename "${0}") ${PARAMS}"
            echo
            echo "The error was:"
            echo
            echo "$*"
            echo "\`\`\`"
        } > /tmp/death-tg-msg
        notify "$(cat /tmp/death-tg-msg)"
    fi

    display_error "$@"
    exit
}

# Prints a warning in bold yellow
function warn() {
    echo
    echo "${YLW}${1}${RST}"
    if [[ -z ${2} ]]; then
        echo
    fi
}

# Enforces the value needed for two-part flags
function enforce_value() {
    if [[ $# -lt 1 ]]; then
        die "A additional value is needed for one of the flags passed to this script!"
    fi
}

# Add a remote if it doesn't exist
function add_remote() {
    if ! git remote | grep -q -m 1 "${1}"; then
        git remote add "${1}" "${2}"
    fi
}

# Convert a file location to web link
function web_link() {
    echo "${1}" | sed s/"$(echo "${WEB_FOLDER}" | sed 's/\//\\\//g')"/http:\\/\\/nchancellor.net/
}

# Set up a virtual environment for Python
function mkavenv {
    virtualenv2 "${HOME}/venv"
    source "${HOME}/venv/bin/activate"
}

# Remove virtual environment
function rmvenv {
    deactivate
    rm -rf "${HOME}/venv"
}

# Source Telegram bot information
function load_botinfo() {
    if [[ -f ${HOME}/.botinfo ]]; then
        source ~/.botinfo
    fi
}

load_botinfo

# Require a parameter to opt out of macOS_check
if [[ $# -lt 1 && ${OS} = "darwin" ]]; then
    die "Wrong window! ;)"
fi

# Telegram notifier function
function notify() {
    if [[ -z ${TOKEN} ]]; then
        display_error "notify() was called but there was no token!"
        return 1
    fi

    if [[ -z ${CHAT_ID} ]]; then
        display_error "notify() was called but there was no chat ID!"
        return 1
    fi

    curl -s -X POST https://api.telegram.org/bot${TOKEN}/sendMessage -d chat_id=${CHAT_ID} -d parse_mode="Markdown" -d text="$@" 1>/dev/null
}
