#!/usr/bin/env bash
#
# Script to update and install crosstool-NG
#
# Copyright (C) 2017 Nathan Chancellor
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>


################
#              #
#  PARAMETERS  #
#              #
################

# SOURCE OUR UNIVERSAL FUNCTIONS SCRIPT AND MAC CHECK
source common

# GATHER PARAMETERS
while [[ $# -ge 1 ]]; do
    case ${1} in
        # ONLY BUILD CROSSTOOL-NG
        "-b"|"--build-only")
            BUILD_ONLY=true ;;

        # ONLY UPDATE CROSSTOOL-NG REPO
        "-u"|"--update-only")
            UPDATE_ONLY=true ;;

        *)
            report_error "Invalid parameter specified!" ;;
    esac

    shift
done


###############
#             #
#  VARIABLES  #
#             #
###############

BUILD_FOLDER=${TC_FOLDER}/build
SOURCE_FOLDER=${BUILD_FOLDER}/ct-ng


###############
#             #
#  FUNCTIONS  #
#             #
###############

function update() {
    header "UPDATING SOURCES"

    [[ ! -d ${BUILD_FOLDER} ]] && mkdir -p ${BUILD_FOLDER}
    [[ ! -d ${SOURCE_FOLDER} ]] && hub clone crosstool-ng/crosstool-ng ${SOURCE_FOLDER}

    cd ${SOURCE_FOLDER}

    git fetch origin

    [[ $(git rev-list --count HEAD..origin/master) -gt 0 ]] && \
        git log --oneline HEAD..origin/master

    git rebase origin/master
}

function build() {
    [[ ! -d ${SOURCE_FOLDER} ]] && update

    header "BUILDING CROSSTOOL-NG"

    git clean -fxd

    ./bootstrap

    ./configure --prefix=/usr/local

    MAKE="make ${JOBS_FLAG}"

    ${MAKE} clean

    ${MAKE}

    sudo ${MAKE} install

    [[ -f /usr/local/bin/ct-ng ]] && \
    [[ -f ct-ng ]] && header "BUILD SUCCESSFUL!" ${GRN} \
                   || header "BUILD FAILED!" ${RED}
}


################
#              #
# SCRIPT START #
#              #
################

[[ ! ${BUILD_ONLY} ]] && update
[[ ! ${UPDATE_ONLY} ]] && build
