#!/usr/bin/env bash
#
# Script to build a zImage from a kernel tree
#
# Copyright (C) 2017 Nathan Chancellor
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>


# SOURCE OUR UNIVERSAL FUNCTIONS SCRIPT AND MAC CHECK
source common

# START TIME
START=$(date +%s)

# GATHER PARAMETERS
while [[ $# -ge 1 ]]; do
    case ${1} in
        # ARCHITECTURE TO BUILD; DEFAULTS TO ARM64
        "-a"|"--arch")
            shift && enforce_value $@

            ARCH=${1} ;;

        # DEFCONFIG TO BUILD; DEFAULTS TO FLASH_DEFCONFIG
        "-d"|"--defconfig")
            shift && enforce_value $@

            DEFCONFIG=${1} ;;

        # SHOW FULL COMPILATION
        "-D"|"--debug")
            VERBOSITY=2 ;;

        # IMAGE TO TARGET; DEFAULTS TO IMAGE.GZ-DTB
        "-i"|"--image")
            shift && enforce_value $@

            IMAGE=${1} ;;

        # TOOLCHAIN TO COMPILE WITH; DEFAULTS TO A73 TARGETED LINARO 7.x
        "-t"|"--toolchain")
            shift && enforce_value $@

            case ${1} in
                "aosp-gcc")
                    TOOLCHAIN=/opt/${1}/bin/aarch64-linux-android- ;;
                "l-7.x-a73.a53")
                    TOOLCHAIN=/opt/${1}/bin/aarch64-linaro-linux-android- ;;
                "g-8.x")
                    TOOLCHAIN=/opt/${1}/bin/aarch64-gnu-linux-gnu- ;;
                *)
                    TOOLCHAIN=${1} ;;
            esac ;;

        # UPLOAD IMAGE TO TRANSFER.SH
        "-u"|"--upload")
            UPLOAD=true ;;

        # SHOW WARNINGS AND ERRORS DURING COMPILATION
        "-w"|"--warnings")
            VERBOSITY=1 ;;
    esac

    shift
done

# DEFAULTS
if [[ -z ${ARCH} ]]; then
    ARCH=arm64
fi
if [[ -z ${IMAGE} ]]; then
    IMAGE=Image.*-dtb
fi
if [[ -z ${TOOLCHAIN} ]]; then
    TOOLCHAIN=/opt/aosp-gcc/bin/aarch64-linux-android-
fi

# ERROR OUT IF DEFCONFIG WASN'T SUPPLIED
if [[ -z ${DEFCONFIG} ]]; then
    die "Please supply a defconfig!"
fi

# BASIC BUILD FUNCTION
function build() {
    # SET MAKE VARIABLE
    MAKE="make ${JOBS_FLAG} O=out ARCH=${ARCH}"
    
    # REMOVE OUT FOLDER AND REMAKE IT
    rm -rf out && mkdir out && echo

    # MAKE DEFCONFIG
    ${MAKE} ${DEFCONFIG}

    # MAKE KERNEL
    time ${MAKE} CROSS_COMPILE="$(command -v ccache) ${TOOLCHAIN}"
}

# REPORT ERROR IF WE AREN'T IN A TREE WITH A MAKEFILE
if [[ ! -f $(pwd)/Makefile ]]; then
    die "This must be run in a kernel tree!"
fi

# SHOW THE BASE VERSION WE ARE MAKING
header "BUILDING $(make kernelversion)"

# SHOW COMPILATION BASED ON FLAGS
case ${VERBOSITY} in
    "2")
        build ;;
    "1")
        build |& ag --nocolor "error:|warning" ;;
    *)
        build &> /dev/null ;;
esac

# REPORT SUCCESS
FINAL_IMAGE=$(ls out/arch/${ARCH}/boot/${IMAGE})
END=$(date +%s)
if [[ -f ${FINAL_IMAGE} ]]; then
    echo "\n${GRN}BUILT IN $(format_time ${END} ${START})${RST}\n
${BOLD}IMAGE:${RST} ${FINAL_IMAGE}\n
${BOLD}VERSION:${RST} $(cat out/include/config/kernel.release)"
else
    die "Kernel build failed!"
fi

# UPLOAD IMAGE IF NECESSARY
if [[ ${UPLOAD} ]]; then
    echo
    curl --upload-file ${FINAL_IMAGE} https://transfer.sh/${IMAGE}
fi

# ALERT OF SCRIPT END
echo "\n\a"
