#!/usr/bin/env bash
#
# Pull in linux-stable updates to a kernel tree
#
# Copyright (C) 2017 Nathan Chancellor
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>


# Source our universal functions script and Mac check
source common

# Parse the provided parameters
function parse_parameters() {
    while [[ $# -ge 1 ]]; do
        case ${1} in
            # Use git cherry-pick
            "-c"|"--cherry-pick")
                export UPDATE_METHOD=cherry-pick ;;

            # Only update the linux-stable remotes
            "-f"|"--fetch-only")
                export FETCH_REMOTES_ONLY=true ;;

            # Help menu
            "-h"|"--help")
                echo
                echo "${BOLD}Script description:${RST} Merges/cherry-picks Linux upstream into a kernel tree"
                echo
                echo "${BOLD}Optional parameters:${RST}"
                echo "    -c | --cherry-pick"
                echo "        Call git cherry-pick instead of git merge when updating from upstream"
                echo
                echo "    -f | --fetch-only"
                echo "        Simply fetches the linux-stable and linux-stable-rc remotes then exits"
                echo
                echo "    -i | --initial-merge"
                echo "        Do not add a commit log to the merge commit"
                echo
                echo "    -p | --print-latest"
                echo "        Prints the latest version available for the current kernel tree upstream then exits"
                echo
                echo "    -r | --release-candidate"
                echo "        Update to the latest RC revision"
                echo
                echo "    -s | --single-version"
                echo "        Updates to the next immediate version available from linux-stable"
                echo
                echo "    -v | --version"
                echo "        Updates to the specified version (e.g. -v 3.18.78)"
                echo
                echo "${BOLD}Notes:${RST}"
                echo "    1. By default, the latest revision will be merged."
                echo "    2. If you already have a remote for upstream, rename it to linux-stable so that multiple ones do not get added!"
                echo
                exit 1 ;;

            # Don't add a log to the commit message
            "-i"|"--initial-merge")
                export INITIAL_MERGE=true ;;

            # Print the latest version from kernel.org
            "-p"|"--print-latest")
                export PRINT_LATEST=true ;;

            # Use the RC tree for updating
            "-r"|"--release-candidate")
                export RC=true
                export UPDATE_MODE=0 ;;

            # Update to the next available version from kernel.org
            "-s"|"--single-version")
                export UPDATE_MODE=0 ;;

            # Update to the specified version
            "-v"|"--version")
                shift
                [[ $# -lt 1 ]] && die "Please specify a version to update!"

                export UPDATE_MODE=1
                export VERSION_SUPPLIED=${1} ;;

            *)
                die "Invalid parameter!" ;;
        esac

        shift
    done

    # Sanity checks
    [[ ! -f Makefile ]] && die "This is not being run in a kernel tree!" -h
    [[ -z ${UPDATE_METHOD} ]] && export UPDATE_METHOD=merge
    [[ -z ${UPDATE_MODE} ]] && export UPDATE_MODE=2
}


# Update the linux-stable{-rc} remotes (and add them if they doesn't exist)
function verify_remote() {
    add_remote ${1} ${KERNEL_FOLDER}/mirrors/${1}

    git -C ${KERNEL_FOLDER}/mirrors/${1} fetch -p origin
    git fetch ${1}

    [[ $? -ne 0 ]] && die "Remote ${1} update failed!" \
                   || echo "Remote ${1} updated successfully!"
}


# Update the two linux-stable remotes
function update_remotes() {
    header "Updating remotes"

    verify_remote linux-stable
    verify_remote linux-stable-rc

    [[ ${FETCH_REMOTES_ONLY} ]] && echo && exit 0
}


# Generate versions
function generate_versions() {
    header "Calculating versions"

    # Full kernel version
    CURRENT_VERSION=$(make kernelversion)
    # First two numbers (3.4 | 3.10 | 3.18 | 4.4)
    CURRENT_MAJOR_VERSION=$(echo ${CURRENT_VERSION} | cut -f 1,2 -d .)
    # Last number
    CURRENT_SUBLEVEL=$(echo ${CURRENT_VERSION} | cut -d . -f 3)

    # Get latest update from upstream
    LATEST_VERSION=$(git tag --sort=-taggerdate -l v${CURRENT_MAJOR_VERSION}* | head -n 1 | sed s/v//)
    LATEST_SUBLEVEL=$(echo ${LATEST_VERSION} | cut -d . -f 3)

    # Print the current/latest version and exit if requested
    echo "${BOLD}Current kernel version:${RST} ${CURRENT_VERSION}"
    echo
    echo "${BOLD}Latest kernel version:${RST} ${LATEST_VERSION}"
    [[ ${PRINT_LATEST} ]] && echo && exit 0

    # UPDATE_MODES:
    # 0. Update one version
    # 1. Update to a specified version
    # 2. Update to the latest version
    case ${UPDATE_MODE} in
        0)
            TARGET_SUBLEVEL=$((${CURRENT_SUBLEVEL} + 1))
            TARGET_VERSION=${CURRENT_MAJOR_VERSION}.${TARGET_SUBLEVEL} ;;
        1)
            TARGET_VERSION=${VERSION_SUPPLIED} ;;
        2)
            TARGET_VERSION=${LATEST_VERSION} ;;
    esac

    if [[ ${RC} ]]; then
        export TAG=linux-stable-rc/linux-${CURRENT_MAJOR_VERSION}.y
        export RANGE=v${CURRENT_VERSION}..${TAG}
        TARGET_VERSION=${TARGET_VERSION}$(git grep -h "\-rc" ${TAG} -- Makefile | cut -d ' ' -f 3)
    else
        # Make sure target version is between current version and latest version
        TARGET_SUBLEVEL=$(echo ${TARGET_VERSION} | cut -d . -f 3)
        [[ ${TARGET_SUBLEVEL} -le ${CURRENT_SUBLEVEL} ]] && die "Current version is up to date with target version ${TARGET_VERSION}!\n"
        [[ ${TARGET_SUBLEVEL} -gt ${LATEST_SUBLEVEL}  ]] && die "Target version ${TARGET_VERSION} does not exist!\n"
        export RANGE=v${CURRENT_VERSION}..v${TARGET_VERSION}
        export TAG=v${TARGET_VERSION}
    fi

    export CURRENT_MAJOR_VERSION CURRENT_VERSION TARGET_VERSION

    echo
    echo "${BOLD}Target kernel version:${RST} ${TARGET_VERSION}"
    echo
}


function cp_target_version() {
    header "Cherry-picking ${TARGET_VERSION}"

    git cherry-pick ${RANGE}
    [[ $? -ne 0 ]] && die "Cherry-pick needs manual intervention! Resolve conflicts then run:

git add . && git cherry-pick --continue" || header "${TARGET_VERSION} PICKED CLEANLY!" ${GRN}
}


function create_merge_message() {
    MSG_FILE=/tmp/mrg-msg

    rm -rf ${MSG_FILE}

    echo "Merge ${TARGET_VERSION} into $(git rev-parse --abbrev-ref HEAD)" >> ${MSG_FILE}
    if [[ ! ${INITIAL_MERGE} ]]; then
        echo "\nChanges in ${TARGET_VERSION}: ($(git rev-list --count ${RANGE} 2> /dev/null) commits)" >> ${MSG_FILE}
        git log --reverse --format="        %s" ${RANGE} >> ${MSG_FILE}
    fi
    echo "\nSigned-off-by: $(git config --get user.name) <$(git config --get user.email)>" >> ${MSG_FILE}
    CONFLICTS=$(git cf)
    if [[ -n ${CONFLICTS} ]]; then
        echo "\nConflicts:" >> ${MSG_FILE}
        for FILE in ${CONFLICTS}; do
            echo "\t${FILE}" >> ${MSG_FILE}
        done
    fi
}


function mg_target_version() {
    header "Merging ${TARGET_VERSION}"

    GIT_MERGE_VERBOSITY=1 git merge --gpg-sign --no-edit ${TAG}

    if [[ $? -ne 0 ]]; then
        create_merge_message

        die "Merge needs manual intervention! Resolve conflicts then run git km."
    else
        create_merge_message
        git commit --amend --no-edit --quiet --gpg-sign --file ${MSG_FILE}
        header "${TARGET_VERSION} MERGED CLEANLY!" ${GRN}
    fi
}


function update_tree() {
    case ${UPDATE_METHOD} in
        "cherry-pick") cp_target_version ;;
        "merge") mg_target_version ;;
    esac
}


parse_parameters $@
update_remotes
generate_versions
update_tree
