#!/usr/bin/env bash
#
# Utility and terminal setup functions (usually for .bashrc)
#
# Copyright (C) 2017 Nathan Chancellor
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>


# SOURCE OUR UNIVERSAL FUNCTIONS SCRIPT (DON'T MAC CHECK THOUGH)
source common -m

# SOURCE THE OS SPECIFIC FUNCTIONS
source ${SCRIPTS_FOLDER}/os_${OS}

function aliases() {
    # tmux alias
    alias tmux='tmux -u'

    # Alias hub to git
    alias git='hub'

    git config --global alias.aa 'add -A'
    git config --global alias.ac 'commit --signoff --all'
    git config --global alias.b 'branch -v'
    git config --global alias.bd 'branch -D'
    git config --global alias.bm 'branch -m'
    git config --global alias.dc 'diff --cached'
    git config --global alias.dh 'diff HEAD'
    git config --global alias.f 'fetch'
    git config --global alias.fa 'fetch --all'
    git config --global alias.c 'commit --signoff'
    git config --global alias.ca 'commit --amend'
    git config --global alias.ch 'checkout'
    git config --global alias.cp 'cherry-pick'
    git config --global alias.cpa 'cherry-pick --abort'
    git config --global alias.cpc 'cherry-pick --continue'
    git config --global alias.cpe 'cherry-pick --edit'
    git config --global alias.cpq 'cherry-pick --quit'
    git config --global alias.kf 'show -s --format="%h (\"%s\")"'
    git config --global alias.lo 'log --oneline'
    git config --global alias.m 'merge'
    git config --global alias.ma 'merge --abort'
    git config --global alias.mc 'merge --continue'
    git config --global alias.pr 'pull-request'
    git config --global alias.psu 'push --set-upstream'
    git config --global alias.rb 'rebase'
    git config --global alias.rba 'rebase --abort'
    git config --global alias.rbc 'rebase --continue'
    git config --global alias.rh 'reset --hard'
    git config --global alias.rhd 'reset HEAD'
    git config --global alias.rs 'reset --soft'
}

# Try to attach via tmux
function tmux_attach() {
    if [[ -z ${TMUX} ]]; then
        ID=$(tmux ls | grep -vm1 attached | cut -d: -f1)
        [[ -z ${ID} ]] && tmux -u new-session \
                       || tmux -u attach-session -t ${ID}
    fi
}

# Add something to PATH but only if it isn't already there
function add_to_path_pre() {
    [[ ! $(echo ${PATH} | ag -s --nocolor ${1}) ]] && export PATH="${1}:${PATH}"
}

function add_to_path_post() {
    [[ ! $(echo ${PATH} | ag -s --nocolor ${1}) ]] && export PATH="${PATH}:${1}"
}

function bash_setup() {
    aliases
    ${OS}_aliases
    tmux_attach
    ${OS}_prompt
    ${OS}_setup
    add_to_path_pre ${SCRIPTS_FOLDER}
}

# bashrc update function
function buf() {
    source ${SCRIPTS_FOLDER}/os_utils
    bash_setup
}

# EXKM to RC converter
function exkm2rc {
    sed -e 's/^/   write /' ${1} > ${2}
}

function gerrit-push {
    local ROM=${1}
    local PROJECT=${2}

    local URL
    local USER=nathanchance

    case ${1} in
        "du")
            URL=gerrit.dirtyunicorns.com
            BRANCH=o8x ;;
        "du-caf")
            URL=gerrit.dirtyunicorns.com
            BRANCH=o8x-caf ;;
        "omni")
            URL=gerrit.omnirom.org
            BRANCH=android-7.1 ;;
        "subs")
            URL=substratum.review
            if [[ ${PROJECT} = "substratum/interfacer" ]]; then
                BRANCH=n-rootless
            else
                BRANCH=n-mr2
            fi ;;
    esac

    if [[ -z ${PROJECT} ]]; then
        PROJECT=$(grep -m 1 "projectname" .git/config | sed 's/\tprojectname = //')
    fi

    if [[ -n ${PROJECT} ]]; then
        PROJECT=$(echo ${PROJECT} | sed 's/DirtyUnicorns\///')
        echo "Executing git push ssh://${USER}@${URL}:29418/${PROJECT} HEAD:refs/for/${BRANCH}"
        git push ssh://${USER}@${URL}:29418/${PROJECT} HEAD:refs/for/${BRANCH}
    else
        echo "wtf happened?"
    fi
}

function ex () {
	if [[ -f ${1} ]]; then
		case ${1} in
            *.tar.bz2)
                tar xjf ${1} ;;
            *.tar.gz)
                tar xzf ${1} ;;
            *.bz2)
                bunzip2 ${1} ;;
            *.rar)
                unrar x ${1} ;;
            *.gz)
                gunzip ${1} ;;
            *.tar)
                tar xf ${1} ;;
            *.tbz2)
                tar xjf ${1} ;;
            *.tgz)
                tar xzf ${1} ;;
            *.zip)
                unzip ${1} ;;
            *.Z)
                uncompress ${1} ;;
            *.7z)
                7z x ${1} ;;
            *)
                echo "'${1}' cannot be extracted via ex()" ;;
		esac
	else
		echo "'${1}' is not a valid file"
	fi
}

function transfer() {
    echo
    curl --upload-file ${1} https://transfer.sh/$(basename ${1})
    echo
    echo
}

function haste() {
    local OUTPUT CONTENTS

    if (( $# == 0 )) && [[ $(printf "%s" "${0}" | wc -c) > 0 ]]; then
        CONTENTS=${0}

    elif (( $# != 1 )) || [[ $1 =~ ^(-h|--help)$ ]]; then
        echo "Usage: ${0} FILE"
        echo "Upload contents of plaintext document to hastebin."
        echo "\nInvocation with no arguments takes input from stdin or pipe."
        echo "Terminate stdin by EOF (Ctrl-D)."
        return 1

    elif [[ -e ${1} && ! -f ${1} ]]; then
        echo "Error: Not a regular file."
        return 1

    elif [[ ! -e ${1} ]]; then
        echo "Error: No such file."
        return 1

    elif (( $(stat -c %s ${1}) > (512*1024**1) )); then
        echo "Error: File must be smaller than 512 KiB."
        return 1
    fi

    if [[ -n ${CONTENTS} ]] || [[ $(printf "%s" "${CONTENTS}" | wc -c) < 1 ]]; then
        CONTENTS=$(cat ${1})
    fi

    OUTPUT=$(curl -X POST -s -d "${CONTENTS}" https://hastebin.com/documents |\
             awk -F '"' '{print "https://hastebin.com/"$4}')

    if [[ -n ${OUTPUT} ]]; then
        echo ${OUTPUT}
        return 0
    fi
    echo "Upload failed."
    return 1
}
