#!/usr/bin/env bash
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2018 Nathan Chancellor
#
# Pull in android-linux-stable updates to various ROM and custom kernel trees


source "$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" || return; pwd)/common"
trap 'echo; die "Manually aborted!"' SIGINT SIGTERM
ROMS_HOME=${HOME}/kernels/roms




# 3.18 kernels
# SC2076: Don't quote rhs of =~, it'll match literally rather than as a regex.
# shellcheck disable=SC2076
if [[ ${#} -lt 1 || "${*}" =~ "3.18" ]]; then
    # GZR OnePlus 3 (downstream of op3)
    cd "${ROMS_HOME}/gzr-op3" || die "gzr-op3 does not exist, please clone!"
    CURRENT_BRANCH=$(git cb)
    git fetch origin
    git reset --hard origin/"${CURRENT_BRANCH}"
    git fetch als || die "android-linux-stable remote doesn't exist, please add then continue!"
    git ml --no-edit als/lineage-15.1 || die "Merge conflicts detected, please resolve then continue!"
    git push -f nathanchance HEAD:"${CURRENT_BRANCH}" || die "Can't push source to fork!"
    hub pull-request -b "${CURRENT_BRANCH}" -m "Merge $(make kernelversion) into ${CURRENT_BRANCH}"
fi




# 4.4 kernels
# SC2076: Don't quote rhs of =~, it'll match literally rather than as a regex.
# shellcheck disable=SC2076
if [[ ${#} -lt 1 || "${*}" =~ "4.4" ]]; then
    # AICP OnePlus 5 (downstream of op5)
    cd "${ROMS_HOME}/aicp-op5" || die "aicp-op5 does not exist, please clone!"
    CURRENT_BRANCH=$(git cb)
    git fetch origin
    git ml --no-edit origin/"${CURRENT_BRANCH}" || die "Merge conflicts detected, please resolve then continue!"
    git fetch als || die "android-linux-stable remote doesn't exist, please add then continue!"
    git ml --no-edit als/oneplus/QC8998_O_8.1 || die "Merge conflicts detected, please resolve then continue!"
    git push -f nc HEAD:"${CURRENT_BRANCH}" || die "Can't push source to fork!"

    # LineageOS Moto Z2 Force
    cd "${ROMS_HOME}"/lineage-nash || die "lineage-nash does not exist, please clone!"
    git ch lineage-15.1
    git f origin
    git rh origin/"$(git cb)"
    git f LineageOS || die "LineageOS remote does not exist!"
    git ml --no-edit LineageOS/"$(git cb)" || die "Merge conflicts detected, please resolve then continue!"

    merge-stable
    VERSION_44=$(make CROSS_COMPILE="" kernelversion)
    PATCHES_44=${SCRIPTS_FOLDER}/stable-patches/${VERSION_44}
    [[ -f ${PATCHES_44}/nash-lineage-15.1-commands ]] && bash "${PATCHES_44}/nash-lineage-15.1-commands" "v${VERSION_44}"

    git push

    # GZR OnePlus 5 (downstream of op5)
    cd "${ROMS_HOME}/gzr-op5" || die "gzr-op5 does not exist, please clone!"
    CURRENT_BRANCH=$(git cb)
    git fetch origin
    git reset --hard origin/"${CURRENT_BRANCH}"
    git fetch als || die "android-linux-stable remote doesn't exist, please add then continue!"
    git ml --no-edit als/lineage-15.1 || die "Merge conflicts detected, please resolve then continue!"
    git push -f nathanchance HEAD:"${CURRENT_BRANCH}" || die "Can't push source to fork!"
    hub pull-request -b "${CURRENT_BRANCH}" -m "Merge $(make kernelversion) into ${CURRENT_BRANCH}"
fi
