#!/usr/bin/env bash
#
# Zip signing script
#
# Copyright (C) 2017 Nathan Chancellor
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>


###############
#             #
#  FUNCTIONS  #
#             #
###############

# SOURCE OUR UNIVERSAL FUNCTIONS SCRIPT (DON'T MAC CHECK)
source common -m


################
#              #
#  PARAMETERS  #
#              #
################

while [[ $# -ge 1 ]]; do
    case ${1} in
        # FILE TO SIGN
        "-f"|"--file")
            shift && enforce_value $@

            FILE=${1} ;;

        # KEY TO USE
        "-k"|"--key")
            shift && enforce_value $@

            KEY=${1} ;;

        *)
            report_error "Invalid parameter!" ;;
    esac

    shift
done

# Defaults and sanity check
[[ -z ${FILE} ]] && report_error "You didn't specify a file!"
[[ -z ${KEY} ]] && KEY=testkey

# Error out if the file isn't a zip file
[[ $(echo ${FILE} | grep -v zip) ]] && report_error "This can only sign zip files!"


##############
#            #
#  SIGN ZIP  #
#            #
##############

# Show some text
header "Signing ${FILE}"

# Shift to the folder containing the zip
cd $(dirname ${FILE})

# Get the zip name
ZIP_NAME=$(basename ${FILE} .zip)

# Sign the zip
java -jar ${BIN_FOLDER}/signapk.jar \
          ${BIN_FOLDER}/${KEY}.x509.pem \
          ${BIN_FOLDER}/${KEY}.pk8 \
          ${ZIP_NAME}.zip \
          ${ZIP_NAME}-firstsign.zip

${BIN_FOLDER}/zipadjust ${ZIP_NAME}-firstsign.zip \
                     ${ZIP_NAME}-adjusted.zip &>/dev/null

java -jar ${BIN_FOLDER}/minsignapk.jar \
          ${BIN_FOLDER}/${KEY}.x509.pem \
          ${BIN_FOLDER}/${KEY}.pk8 \
          ${ZIP_NAME}-adjusted.zip \
          ${ZIP_NAME}-signed.zip
          
# Remove intermediate zip files
rm ${ZIP_NAME}-firstsign.zip ${ZIP_NAME}-adjusted.zip

# Echo zip location
echo "Signed zip: $(pwd)/${ZIP_NAME}-signed.zip\n"
