FROM docker.io/fedora:rawhide

COPY distrobox-check.fish /
COPY dwarves-1.24.tar.xz /tmp
COPY f01e5f3a849558b8ed6b310686d10738f4c2f3bf.patch /tmp
COPY setup-env.sh /
RUN bash /setup-env.sh && fish /distrobox-check.fish && rm /distrobox-check.fish /setup-env.sh

CMD ["/usr/bin/fish", "-l"]
