#!/usr/bin/env zsh
# SHELL=/home/nathan/usr/bin/zsh
# */1 * * * * /usr/bin/flock -n /tmp/lock.term /home/nathan/github/scripts/cron/packet_spot_market

LOG=/home/nathan/logs/cron-$(TZ=MST date +%Y%m%d).log
SCRIPTS=/home/nathan/github/scripts

source "${SCRIPTS}"/env/folders
source "${SCRIPTS}"/common
mkdir -p "${LOG%/*}"

ERROR_MSG="Metadata API could not be reached at $(TZ=MST date +"%Y/%m/%d %T %Z")"
curl -s -m 10 https://metadata.packet.net/metadata || echo "${ERROR_MSG}" >> "${LOG}"

TIME=$(curl -s https://metadata.packet.net/metadata | jq -r .termination_date)
SERVER=$(curl -s https://metadata.packet.net/metadata | jq -r .class)
{ [[ -z ${TIME} && -z ${SERVER} ]] || [[ ${TIME} = "null" && ${SERVER} = "null" ]]; } && echo "${ERROR_MSG}" >> "${LOG}"

MSG="${SERVER}: Termination time is ${TIME} at $(TZ=MST date +"%Y/%m/%d %T %Z")"
if [[ ${TIME} = "null" || -z ${TIME} ]]; then
    echo "${MSG}" >> "${LOG}"
else
    tg_msg "${MSG}"
fi
