#!/usr/bin/env zsh
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2021 Nathan Chancellor
#
# Update ClangBuiltLinux master branches for LLVM, Clang, and Linux
# */5 * * * * /usr/bin/flock -n /tmp/lock.mirrors /home/nathan/github/scripts/crons/update_mirrors

LOG=${HOME}/cbl/mirrors/logs/$(date +%F)

function log() {
    echo "$(date): ${1}" >>"${LOG}"
}

mkdir -p "$(dirname "${LOG}")"
for REPO in LLVM Linux; do
    case ${REPO} in
        LLVM) BRANCH=main ;;
        Linux) BRANCH=master ;;
    esac
    cd "${HOME}/cbl/mirrors/${REPO:l}" || {
        log "${REPO} folder doesn't exist!"
        continue
    }
    git pull github ${BRANCH} || {
        log "Updating ${REPO} from GitHub failed!"
        continue
    }
    git pull origin ${BRANCH} || {
        log "Updating ${REPO} from origin failed!"
        continue
    }
    git push github HEAD:${BRANCH} || {
        log "Pushing to GitHub failed!"
        continue
    }
    if [[ ${REPO} = "Linux" ]]; then
        git push -f github ${BRANCH}:for-review || {
            log "Pushing for-review branch failed!"
            continue
        }
    fi
    log "${REPO} update successful"
done
echo >>"${LOG}"
