#!/usr/bin/env bash
# Update ClangBuiltLinux master branches for LLVM, Clang, and Linux
# */5 * * * * /usr/bin/flock -n /tmp/lock.mirrors /home/nathan/scripts/crons/update_mirrors

LOG=${HOME}/kernels/mirrors/logs/$(date +%Y%m%d)

function log() {
    echo "$(date): ${1}" >> "${LOG}"
}

mkdir -p "$(dirname "${LOG}")"
for REPO in Clang LLVM Linux; do
    cd "${HOME}/kernels/mirrors/${REPO,,}" || { log "${REPO} folder doesn't exist!"; continue; }
    git pull github master || { log "Updating ${REPO} from GitHub failed!"; continue; }
    git pull origin master || { log "Updating ${REPO} from origin failed!"; continue; }
    git push github HEAD || { log "Pushing to GitHub failed!"; continue; }
    log "${REPO} update successful"
done
echo >> "${LOG}"
