[Match]
Distribution=arch

[Content]
Packages=
        amd-ucode
        dbus
        dbus-broker
        linux
        networkmanager
        openssh
        pacman-hook-kernel-install
        systemd
