[Match]
Distribution=arch

[Content]
Packages=
        # base
        base
        openssh
        pacman-contrib
        systemd-sysvcompat
        tzdata

        # env
        fish
        tmuxp
        vim-spell-en

        # man pages
        man-db

        # nicer GNU utilities
        bat-extras
        diskus
        duf
        eza
        fd

        # python / uv
        python
        uv

        # system administration
        reflector

[Distribution]
Repositories=core-testing,extra-testing
