#!/usr/bin/env bash

PATCHES_FOLDER=$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)
git ra
if [[ "${*}" =~ "--no-als" ]]; then
    for FILE in assembler.h auditsc.c base.c cputype.h vmscan.c; do
        git ap "${PATCHES_FOLDER}"/flash/"${FILE}".diff
    done
else
    git ap "${PATCHES_FOLDER}"/flash/cputype.h.diff
    [[ "$(pwd)" =~ "op5" ]] && git ap "${PATCHES_FOLDER}"/flash/assembler.h.diff
fi
git ap "${PATCHES_FOLDER}"/flash/futex.h.diff
if [[ "${*}" =~ "--no-als" ]]; then
    git fm
else
    git mc
fi
