#!/usr/bin/env bash

PATCHES_FOLDER=$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)
git ra
git ap -3 "${PATCHES_FOLDER}/jiffies.h.diff"
git ap -3 "${PATCHES_FOLDER}/nf_nat_h323.c.diff"
git ap -3 "${PATCHES_FOLDER}/task_mmu.c.diff-wahoo"
git fm
