#!/usr/bin/env bash
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2018 Nathan Chancellor
#
# Utility and terminal setup functions for Termux on Android


# Fetch this script and reload .bashrc
function rld() {
    curl -o ~/.bashrc https://raw.githubusercontent.com/nathanchance/scripts/master/os/android
    source ~/.bashrc
}


# Update function
function upd() {
    pkg upgrade
}


# Function to upload to del.dog
function deldog() {
    RESULT=$(curl -sf --data-binary @"${1:--}" https://del.dog/documents) || {
        echo "ERROR: failed to post document" >&2
        return 1
    }
    KEY=$(jq -r .key <<< "${RESULT}")
    echo "https://del.dog/raw/${KEY}"
}


# Common WireGuard logs
function wg_debug() {
    COMMANDS=( "wg" "ip addr show" "iptables -L -v" "ip6tables -L -v" "dmesg" )
    {
        for COMMAND in "${COMMANDS[@]}"; do
            su --preserve-environment -c "${COMMAND}"
            echo
            echo
        done
    } | deldog
}
