#!/usr/bin/env bash
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2018 Nathan Chancellor
#
# Utility and terminal setup functions for my Pixelbook


# Fetch this script and reload .bashrc
function rld() {
    curl -o ~/.chromeos-functions https://raw.githubusercontent.com/nathanchance/scripts/master/os/chromeos
    source ~/.bashrc
}


# Set vim runtime area
export VIMRUNTIME=/usr/local/share/vim/vim80


# Neofetch function
function neofetch() {
    echo
    $(which neofetch) --distro_shorthand tiny "$@"
    echo
}


# Function to upload to del.dog
function deldog() {
    RESULT=$(curl -sf --data-binary @"${1:--}" https://del.dog/documents) || {
        echo "ERROR: failed to post document" >&2
        return 1
    }
    KEY=$(jq -r .key <<< "${RESULT}")
    echo "https://del.dog/${KEY}"
    echo "https://del.dog/raw/${KEY}"
}


# adb needs to be executed as root and have HOME defined in a writable folder
function adb() {
    sudo su --preserve-environment -c "HOME=$(cd /home/user/* || return; pwd) $(which adb) $*"
}


# fastboot needs to be executed as root and have HOME defined in a writable folder
function fastboot() { 
    sudo su --preserve-environment -c "HOME=$(cd /home/user/* || return; pwd) $(which fastboot) $*"
}


# Update function
function upd() {
    crew update
    crew upgrade
}


# Downloads folder
alias dwnld='cd ${HOME}/Downloads'
# Files folder
alias fls='cd ${HOME}/Downloads/Files'


# Make hostname 'flashbook'
sudo hostname flashbook
