#!/usr/bin/env bash
#
# Utility and terminal setup functions for my Pixelbook
#
# Copyright (C) 2018 Nathan Chancellor
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>


# Fetch this script and reload .bashrc
function rld() {
    curl -o ~/.chromeos-functions https://raw.githubusercontent.com/nathanchance/scripts/master/os/chromeos
    source ~/.bashrc
}


# Set vim runtime area
export VIMRUNTIME=/usr/local/share/vim/vim80


# Neofetch function
function neofetch() {
    echo
    $(which neofetch) --distro_shorthand tiny "$@"
    echo
}


# Function to upload to del.dog
function deldog() {
    RESULT=$(curl -sf --data-binary @"${1:--}" https://del.dog/documents) || {
        echo "ERROR: failed to post document" >&2
        return 1
    }
    KEY=$(jq -r .key <<< "${RESULT}")
    echo "https://del.dog/${KEY}"
    echo "https://del.dog/raw/${KEY}"
}


# adb needs to be executed as root and have HOME defined in a writable folder
function adb() {
    sudo su --preserve-environment -c "HOME=$(cd /home/user/* || return; pwd) $(which adb) $*"
}


# fastboot needs to be executed as root and have HOME defined in a writable folder
function fastboot() { 
    sudo su --preserve-environment -c "HOME=$(cd /home/user/* || return; pwd) $(which fastboot) $*"
}


# Update function
function update() {
    crew update
    crew upgrade
}
