#!/usr/bin/env bash
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2018 Nathan Chancellor
#
# Utility and terminal setup functions for my Pixelbook


# Downloads folder
alias dwnld='cd ${HOME}/Downloads'

# Files folder
alias fls='cd ${HOME}/Downloads/Files'

# Connect to my server
alias mshfb='mosh nathan@nathanchance.me'

# Make hostname 'flashbook'
sudo hostname flashbook


# Fetch this script and reload .bashrc
function rld() {
    curl -o ~/.chromeos-functions https://raw.githubusercontent.com/nathanchance/scripts/master/os/chromeos
    source ~/.bashrc
}


# Set vim runtime area
export VIMRUNTIME=/usr/local/share/vim/vim80


# Neofetch function
function neofetch() {
    echo
    /usr/local/bin/neofetch --distro_shorthand tiny "${@}"
    echo
}


# Function to upload to del.dog
function deldog() {
    RESULT=$(curl -sf --data-binary @"${1:--}" https://del.dog/documents) || {
        echo "ERROR: failed to post document" >&2
        return 1
    }
    KEY=$(jq -r .key <<< "${RESULT}")
    echo "https://del.dog/raw/${KEY}"
}


# Update function
function upd() {
    crew update
    crew upgrade
}


# Reinstall function in case Chromebrew blows up...
function reinstall() {
    # Wipe /usr/local and reinstall emerge packages
    sudo dev_install --reinstall -y

    # Reinstall adb/fastboot
    curl -s https://raw.githubusercontent.com/nathanchance/chromeos-adb-fastboot/master/install.sh | bash

    # Reinstall neofetch
    sudo curl -s https://raw.githubusercontent.com/dylanaraps/neofetch/master/neofetch -o /usr/local/bin/neofetch
    sudo chmod a+x /usr/local/bin/neofetch

    # Reload functions
    rld
}


# Generate new SSH key for server interaction
function gen-ssh() {
    ssh-keygen -t rsa
    ssh-copy-id nathan@94.130.39.26
}
