#!/usr/bin/env bash
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2017-2018 Nathan Chancellor
#
# Utility and terminal setup functions for my build server


# Build server specific aliases
function flashbox_aliases() {
    # default Arch ls alias
    alias ls='ls --color=auto'

    # Update alias
    alias upd='aurman -Syyu'

    # Change directory aliases
    alias 6p='cd ${KERNEL_FOLDER}/flash/angler'
    alias ack='cd ${KERNEL_FOLDER}/sources/kernel-common'
    alias asu='cd ${REPO_FOLDER}/asu'
    alias cros='cd ${KERNEL_FOLDER}/sources/chromium'
    alias lnx='cd ${KERNEL_FOLDER}/sources/linux'
    alias pkg='cd ${REPO_FOLDER}/pkgbuilds'
    alias op6='cd ${KERNEL_FOLDER}/flash/op6'
    alias op6ak='cd ${KERNEL_FOLDER}/flash/anykernel2-op6'
    alias pi='cd ${KERNEL_FOLDER}/pi'
    alias pxl='cd ${KERNEL_FOLDER}/flash/marlin'
    alias pxlak='cd ${KERNEL_FOLDER}/flash/anykernel2-marlin'
    alias pxl2='cd ${KERNEL_FOLDER}/flash/wahoo'
    alias pxl2ak='cd ${KERNEL_FOLDER}/flash/anykernel2-wahoo'
    alias tlc='cd ${TC_FOLDER}'
    alias sod='cd ${KERNEL_FOLDER}/sony/kernel'
    alias spt='cd ${SCRIPTS_FOLDER}'

    # Generate a kernel version for the current tree
    alias kver='make kernelversion'

    # Setup build for AOSP
    alias senv='. build/envsetup.sh'

    # Alias for flash-kernel script
    alias fk='flash-kernel'

    # Alias for merge-stable script
    alias ms='merge-stable'

    # Clean out web folder
    alias wfc='git -C ${WEB_FOLDER}/downloads/kernels cl'

    # Git aliases
    git config --global alias.m 'merge --gpg-sign --signoff'
    git config --global alias.ml 'merge --gpg-sign --signoff --log=500'
    git config --global alias.pl 'pull --gpg-sign --signoff'
    git config --global alias.pll 'pull --gpg-sign --signoff --log=500'
}


# Setup PS1 and such
function flashbox_prompt() {
    source ~/.git-prompt.sh
    export GIT_PS1_SHOWDIRTYSTATE=1
    export GIT_PS1_SHOWUPSTREAM=auto
    export PROMPT_COMMAND='__git_ps1 "\[\033[01;34m\]\u@\h \[\033[01;32m\]\w\[\033[01;31m\]" " \[\033[39m\]\$\[\033[0m\] "'
}


# Setup ccache
# ccache_setup <size>
function ccache_setup() {
    if [[ -f ${CCACHE} ]]; then
        if [[ -n ${1} ]]; then
            ccache -M "${1}"G &> /dev/null
            export USE_CCACHE=1
            add_to_path_pre "/usr/lib/ccache/bin"
        else
            display_error "Please specify ccache size!"
        fi
    else
        display_error "Please install ccache!"
    fi
}


# Additional setup steps for my build server
function flashbox_setup() {
    flashbox_prompt
    ccache_setup 200
    export LOG=/tmp/results.log
    add_to_path_post "${HOME}/.gem/ruby/2.5.0/bin"
}


# Repo sync shorthand
# SC2120: rps references arguments, but none are ever passed.
# shellcheck disable=SC2120
function rps {
    repo sync "${JOBS_FLAG}" --force-sync -c --no-clone-bundle --no-tags --optimized-fetch --prune "${@}"
}


# Repo init and sync function
# ris <url> <branch> |-s|
function ris {
    # User requested a shallow clone
    [[ ${3} = "-s" ]] && local DEPTH="--depth=1"

    repo init -u "${1}" -b "${2}" --no-clone-bundle ${DEPTH}

    # SC2119: Use rps "$@" if function's $1 should mean script's $1.
    # shellcheck disable=SC2119
    time rps
}


# Add kernel remotes to a kernel repo
function kremotes() {
    if [[ ! -f Makefile ]]; then
        display_error "Run this in a kernel tree!"
        return 1
    fi

    git remote add aosp-kc https://android.googlesource.com/kernel/common
    git remote add aosp-msm https://android.googlesource.com/kernel/msm
    git remote add chromium https://chromium.googlesource.com/chromiumos/third_party/kernel
    git remote add msm-4.4 https://source.codeaurora.org/quic/la/kernel/msm-4.4
    git remote add linux https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
    git remote add linux-stable https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
    git remote add linux-stable-rc https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git

    git remote update
}


# Neofetch alias
function nf() {
    echo
    neofetch \
        --kernel_shorthand on \
        --distro_shorthand tiny \
        --os_arch off \
        --uptime_shorthand tiny \
        --speed_shorthand on \
        --install_time off \
        --color_blocks off \
        "${@}"
    echo
    echo
}


# Find config values in a kernel tree
# kfg [-c <defconfig_file>] [-f <config>] [-e <config>] [-d <config>]
function kfg() {
    local CONFIG DEFCONFIGS LIST
    DEFCONFIGS="$(ls arch/arm64/configs/flash*_defconfig 2>/dev/null)"

    while [[ ${#} -ge 1 ]]; do
        case ${1} in
            "-c"|"--config")
                shift

                DEFCONFIGS=${1} ;;

            "-d"|"--disable")
                shift

                CONFIG=${1//CONFIG_/}
                for DEFCONFIG in ${DEFCONFIGS}; do
                    echo "# CONFIG_${CONFIG} is not set" >> arch/arm64/configs/"$(basename "${DEFCONFIG}")"
                done ;;

            "-e"|"--enable")
                shift

                CONFIG=${1//CONFIG_/}

                for DEFCONFIG in ${DEFCONFIGS}; do
                    echo "CONFIG_${CONFIG}=y" >> arch/arm64/configs/"$(basename "${DEFCONFIG}")"
                done ;;

            "-f"|"--find")
                shift

                CONFIG=${1//CONFIG_/}

                header "LOCATIONS OF ${CONFIG} IN TREE"
                git grep -n -1 "${CONFIG}" | ag --nocolor Kconfig

                LIST=$(ag --nocolor "${CONFIG}" out/.config)
                if [[ -n ${LIST} ]]; then
                    header "LOCATIONS OF ${CONFIG} IN CONFIG FILE"
                    echo "${LIST}"
                fi

                echo ;;

            "-u"|"--update")
                shift

                for DEFCONFIG in ${DEFCONFIGS}; do
                    [[ "${*}" =~ "-fc" ]] && FILE=out/.config || FILE=out/defconfig
                    rm -rf out
                    make O=out ARCH=arm64 "$(basename "${DEFCONFIG}")"
                    make O=out ARCH=arm64 savedefconfig
                    cp -v "${FILE}" arch/arm64/configs/"$(basename "${DEFCONFIG}")"
                done ;;
        esac

        shift
    done
}


# Release Flash Kernel build for specified device
# frel <device> <version>
function frel() {
    flash-kernel --device "${1}" \
                 --mode stable \
                 --telegram \
                 --version "${2}"
}


# Build Flash Kernel test builds
# ftest <device> <version> <dirty_version> <type>
function ftest() {
    flash-kernel --branch "queue-${2}" \
                 --device "${1}" \
                 --mode "${4}" \
                 --revision "${3}" \
                 --telegram \
                 --version "${2}"
}


# Regenerate Pixel 2 build binaries
function rpb() {
    cd "${KERNEL_FOLDER}/sources/aosp-pixel2" || return

    mkavenv
    . build/envsetup.sh
    lunch aosp_taimen-user
    m "${JOBS_FLAGS}" clean
    m "${JOBS_FLAGS}" mkdtimg
    rmvenv

    cp out/host/linux-x86/bin/mkdtimg "${BIN_FOLDER}"

    cd "${SCRIPTS_FOLDER}" || return

    git status
}


# Sign zip files for TWRP flashability
function signzip() {
    local FILE=${1}
    if echo "${FILE}" | grep -q -v zip; then
        display_error "This can only sign zip files!"
        return 1
    fi
    if [[ ! -f ${FILE} ]]; then
        display_error "Zip file does not exist!"
        return 1
    fi

    header "Signing ${FILE}"

    # Shift to the folder containing the zip
    cd "$(dirname "${FILE}")" || return

    # Get the zip name
    SIGNED_ZIP="$(basename "${FILE}")"
    UNSIGNED_ZIP="$(basename "${FILE}" .zip)-unsigned.zip"

    # Sign the zip
    mv "${SIGNED_ZIP}" "${UNSIGNED_ZIP}"
    java -jar "${BIN_FOLDER}/zipsigner-2.1.jar" \
              "${UNSIGNED_ZIP}" \
              "${SIGNED_ZIP}"
    rm "${UNSIGNED_ZIP}"

    # Echo zip location
    echo "Signed zip: ${PWD}/${SIGNED_ZIP}\n"
    cd "${OLDPWD}" || return
}


# Manage queue tags
# queue-tag [-c|-d] <version> <hash>
function queue-tag() {
    if [[ ! -f Makefile ]]; then
        display_error "Run this in a kernel tree!"
        return 1
    fi

    case ${1} in
        "-c"|"--create")
            git tag -f -a "queue-${2}" -m "Queue for Flash v${2}" -s "${3:-HEAD}"
            git push -f origin "queue-${2}" ;;

        "-d"|"--delete")
            git tag -d "queue-${2}"
            git push origin :"queue-${2}" ;;
    esac
}


# Does it build function
# SC2120: dib references arguments, but none are ever passed.
# shellcheck disable=SC2120
function dib() {(
    DEVICE=$(basename "${PWD}")

    while [[ ${#} -ge 1 ]]; do
        case ${1} in
            "-l"|"--log") WANTS_LOG=true ;;
            "-t"|"--telegram") WANTS_TG=true ;;
        esac
        shift
    done

    [[ -n ${WANTS_LOG} ]] && rm -r "${LOG}"

    # Set common parameter lists
    FLASH_CLANG_7=( "--compiler clang --clang-toolchain flash-clang-7.x" )
    FLASH_CLANG_6=( "--compiler clang --clang-toolchain flash-clang-6.x" )
    AOSP_CLANG_7=( "--compiler clang --clang-toolchain aosp-clang/clang-r328903" )
    AOSP_CLANG_6=( "--compiler clang --clang-toolchain aosp-clang/clang-4691093" )
    AOSP_CLANG_5=( "--compiler clang --clang-toolchain aosp-clang/clang-4053586" )
    GCC_811=( "--compiler gcc --gcc-toolchain btg-gcc-8.1.1-arm64 --gcc-32-bit-toolchain btg-gcc-8.1.1-arm" )
    GCC_731=( "--compiler gcc --gcc-toolchain btg-linaro-gcc-7.3.1-arm64 --gcc-32-bit-toolchain btg-linaro-gcc-7.3.1-arm" )
    GCC_494=( "--compiler gcc --gcc-toolchain aosp-gcc-arm64 --gcc-32-bit-toolchain aosp-gcc-arm" )

    case ${DEVICE} in
        marlin) TC_LIST=( "${FLASH_CLANG_7[@]}" "${FLASH_CLANG_6[@]}" "${AOSP_CLANG_7[@]}" "${AOSP_CLANG_6[@]}" "${GCC_811[@]}" "${GCC_731[@]}" "${GCC_494[@]}" ) ;;
        op6) TC_LIST=( "${FLASH_CLANG_7[@]}" "${FLASH_CLANG_6[@]}" "${AOSP_CLANG_7[@]}" "${AOSP_CLANG_6[@]}" "${GCC_811[@]}" "${GCC_731[@]}" "${GCC_494[@]}" ) ;;
        wahoo) TC_LIST=( "${FLASH_CLANG_7[@]}" "${FLASH_CLANG_6[@]}" "${AOSP_CLANG_7[@]}" "${AOSP_CLANG_6[@]}" "${AOSP_CLANG_5[@]}" "${GCC_811[@]}" "${GCC_731[@]}" "${GCC_494[@]}" ) ;;
        *) display_error "This folder doesn't support dib!"; return ;;
    esac

    for ITEM in "${TC_LIST[@]}"; do
        read -ra ITEM_ARRAY <<< "${ITEM}"
        flash-kernel --device "${DEVICE}" --mode tmp --image-only "${ITEM_ARRAY[@]}"
    done

    clear

    if [[ -n ${WANTS_LOG} ]]; then
        MESSAGE="${BOLD}${DEVICE} results:${RST} $(deldog "${LOG}")"
        echo
        echo "${MESSAGE}"
        echo
        [[ -n ${WANTS_TG} ]] && notify "${MESSAGE}"
    fi
)}


# A version of dib for android-kernel-clang
function dib-clang() {(
    case "$(git cb)" in
        "msm-3.18") DEFCONFIG=msm-perf_defconfig ;;
        "msm-4.4") DEFCONIFG=msmcortex-perf_defconfig ;;
        "msm-4.9") DEFCONFIG=sdm845-perf_defconfig ;;
    esac

    TC_LIST=( "--clang --clang-toolchain aosp-clang/clang-r328903"
              "--clang --clang-toolchain aosp-clang/clang-4691093"
              "--clang --clang-toolchain aosp-clang/clang-4053586"
              "" )

    for ITEM in "${TC_LIST[@]}"; do
        read -ra ITEM_ARRAY <<< "${ITEM}"
        build-kernel -d "${DEFCONFIG}" -w -Werror "${ITEM_ARRAY[@]}"
    done
)}


function ls-stats() {
    if [[ ! -f Makefile ]]; then
        display_error "Run this in a kernel tree!"
        return 1
    fi

    VER=${1}
    SBLVL=$(git tag --sort=-taggerdate -l v"${VER}"* | head -n 1 | sed s/v// | cut -d . -f 3)

    echo "Linux ${VER} was released on $(git log -1 --format=%ai v"${VER}")

The latest version of ${VER} is ${VER}.${SBLVL}, released on $(git log -1 --format=%ai v"${VER}.${SBLVL}")

Number of commits in each version of ${VER}:

v${VER}.1: $(git lo v"${VER}..v${VER}.1" | wc -l)
$(for i in $(seq 2 "${SBLVL}"); do echo "v${VER}.$i: $(git lo "v${VER}.$((i - 1))..v${VER}.$i" | wc -l)"; done)

Average number of commits in a version of ${VER}: $(($(git lo "v${VER}..v${VER}.${SBLVL}" | wc -l) / SBLVL))" > "${HOME}/web/stats/${VER}"
}


# Shellcheck function
function shellcheck() {
    # SC1090: Can't follow non-constant source. Use a directive to specify location.
    # SC1091: Not following: build/envsetup.sh: openBinaryFile: does not exist (No such file or directory)
    # SC1094: Parsing of sourced file failed. Ignoring it.
    # SC1117: Backslash is literal in "\t". Prefer explicit escaping: "\\t".
    # SC2028: echo won't expand escape sequences. Consider printf.
    command shellcheck -x -e SC1090 -e SC1091 -e SC1094 -e SC1117 -e SC2028 "${@}"
}


# Shellcheck wrapper
function sc() {
    if ! [[ "${PWD}" =~ "scripts" ]]; then
        display_error "Not in scripts folder, why are you running sc?"
        return;
    fi

    case ${1} in
        "-a"|"--all") FILES=$(find . -maxdepth 2 -type f -executable  -printf '%P\n' | ag -v bin) ;;
        *) FILES=$(git diff --name-only --diff-filter=M) ;;
    esac

    echo
    for FILE in ${FILES}; do
        if shellcheck "${FILE}"; then
            echo "${GRN}${FILE} is clean of warnings/errors!${RST}"
        fi
    done
    echo
}


# makepkg wrapper for Linux kernel
function mkpkg() {
    local START TIME_STRING
    START=$(date +%s)
    if makepkg -si --noconfirm; then
        TIME_STRING=$(format_time "${START}" "$(date +%s)")
        notify "\`Server kernel build completed successfully in ${TIME_STRING,,}\`"
    else
        notify "\`Server kernel build failed in ${TIME_STRING,,}\`"
    fi
}


# Update all remotes and run git gc/prune
function clean-kernels() {
    REPOS="
${HOME}/kernels/als/marlin
${HOME}/kernels/als/msm-3.18
${HOME}/kernels/als/msm-4.4
${HOME}/kernels/als/msm-4.9
${HOME}/kernels/als/nash
${HOME}/kernels/als/op3
${HOME}/kernels/als/op5
${HOME}/kernels/als/op6
${HOME}/kernels/als/sagit
${HOME}/kernels/als/tissot
${HOME}/kernels/als/wahoo
${HOME}/kernels/als/whyred
${HOME}/kernels/flash/marlin
${HOME}/kernels/flash/op6
${HOME}/kernels/flash/wahoo
${HOME}/kernels/pi
${HOME}/kernels/roms/gzr-op3
${HOME}/kernels/roms/gzr-op5
${HOME}/kernels/roms/lineage-nash
${HOME}/kernels/roms/lineage-op6
${HOME}/kernels/sony/kernel"

    for REPO in ${REPOS}; do
        header "${REPO}"
        if cd "${REPO}"; then
            git fetch --all
            git reflog expire --all --expire=now
            git gc --aggressive --prune=now --force
        else
            display_error "$(basename "${REPO}") doesn't exist!"
        fi
    done
}


# Update AnyKernel2 from osm0sis's GitHub
function update-ak2() {(
    REPOS="
${HOME}/kernels/flash/anykernel2-marlin
${HOME}/kernels/flash/anykernel2-op6
${HOME}/kernels/flash/anykernel2-wahoo"

    for REPO in ${REPOS}; do
        header "Updating $(basename "${REPO}")"

        cd "${REPO}" || {
            display_error "${REPO} does not exist, please clone it from GitHub!"
            return 1
        }

        if ! git ls-remote --exit-code upstream 1>/dev/null; then
            git remote add upstream https://github.com/osm0sis/AnyKernel2
        fi

        CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

        git ch -q master
        git pull -q upstream master
        git push -q

        git ch -q "${CURRENT_BRANCH}"
        if ! git ml --no-edit master; then
            display_error "Conflicts detected! Please fix them then run 'git mc'"
            return 1
        fi
        git push -q
    done
    echo
)}


# Build android/common kernel
function ac-kernel() {
    local UPDATE VERSION
    cd "${HOME}/kernels/sources/kernel-common" || return

    while [[ ${#} -ge 1 ]]; do
        case ${1} in
            "-u"|"--update") UPDATE=true ;;
            *) VERSION=${1} ;;
        esac

        shift
    done
    echo

    [[ -z ${VERSION} ]] && VERSION=4.4
    
    # Checkout proper branch
    git checkout -q "android-${VERSION}"

    # Update
    [[ -n ${UPDATE} ]] && git pull

    # Configure
    git clean -fxdq
    mkdir -p out
    {
        case ${VERSION} in
            "4.4") ./android/configs/android-fetch-configs.sh ;;
            *) ./kernel/configs/android-fetch-configs.sh ;;
        esac
        cat arch/arm64/configs/defconfig \
            android-base.cfg \
            android-base-arm64.cfg \
            android-recommended.cfg > out/.config
        make ARCH=arm64 O=out olddefconfig prepare
    } &> /dev/null

    # Build the kernel
    time make "${JOBS_FLAG}" \
              ARCH=arm64 \
              CC="${CCACHE} ${TC_FOLDER}/aosp-clang/clang-r328903/bin/clang" \
              CLANG_TRIPLE=aarch64-linux-gnu- \
              CROSS_COMPILE="${TC_FOLDER}/aosp-gcc-arm64/bin/aarch64-linux-android-" \
              O=out > /dev/null

    # Show version information
    if [[ -f out/arch/arm64/boot/Image ]]; then
        echo "\n${GRN}Kernel build successful!${RST}"
        echo "\n${BOLD}Kernel version:${RST} $(cat out/include/config/kernel.release)"
    else
        display_error "Kernel build failed!"
    fi
    echo
}


# build-kernel wrapper for known trees
function bk() {
    local FOLDER PARAMS

    FOLDER=$(basename "${PWD}")

    case "${FOLDER}:$(git cb)" in
        # Custom ROMs
        "du-op5:o8x-caf"*) PARAMS=( oneplus5_defconfig -c ) ;;
        "gzr-op3:"*) PARAMS=( lineageos_oneplus3_defconfig ) ;;
        "gzr-op5:"*|"aicp-op5:"*) PARAMS=( lineage_oneplus5_defconfig -c ) ;;
        "lineage-nash:lineage-15.1") PARAMS=( lineageos_nash_defconfig -c ) ;;
        "lineage-op6:"*) PARAMS=( enchilada_defconfig ) ;;

        # android-linux-stable
        "angler:"*|"bullhead:"*|"marlin:"*) PARAMS=( "${FOLDER}_defconfig" ) ;;
        "mata:lineage-15.1") PARAMS=( "lineageos_${FOLDER}_defconfig" -c ) ;;
        "msm-3.18:"*|"msm-4.4:"*) PARAMS=( msmcortex-perf_defconfig ) ;;
        "msm-4.9:"*) PARAMS=( sdm845-perf_defconfig ) ;;
        "op3:android-8.1") PARAMS=( omni_oneplus3_defconfig ) ;;
        "op3:lineage-15.1") PARAMS=( lineageos_oneplus3_defconfig ) ;;
        "op3:oneplus/QC8996_O_8.0.0"*) PARAMS=( msm-perf_defconfig ) ;;
        "op5:android-8.1") PARAMS=( omni_oneplus5_defconfig ) ;;
        "op5:lineage-15.1") PARAMS=( lineage_oneplus5_defconfig ) ;;
        "op5:oneplus/QC8998_O_8."*) PARAMS=( msmcortex-perf_defconfig ) ;;
        "op6:oneplus/SDM845_O_8.1") PARAMS=( sdm845-perf_defconfig ) ;;
        "sagit:sagit-o-oss") PARAMS=( sagit_user_defconfig ) ;;
        "tissot:tissot-o-oss") PARAMS=( tissot-perf_defconfig ) ;;
        "wahoo:"*) PARAMS=( wahoo_defconfig -c ) ;;
        "whyred:whyred-o-oss") PARAMS=( whyred-perf_defconfig ) ;;

        # Franco Kernel
        "op3:oreo"|"mido:oreo-treble"|"tissot:oreo"*) PARAMS=( franco_defconfig ) ;;

        # Unknown choice
        *) display_error "Kernel not supported by wrapper!" && return 1 ;;
    esac

    build-kernel -w -d "${PARAMS[@]}" "${@}"
}


# Change email for git repositories
function change-email() {
    if [[ ${#} -lt 1 ]]; then
        display_error "This function takes an argument!"
        return 1
    fi

    case ${1} in
        "du")
            git config user.email "nathan@dirtyunicorns.com"
            git config user.signingkey 8B07CAAD4B2581BA302A0DB1BA74F524ACD387E1 ;;
        "prjkt")
            git config user.email "nathan@prjkt.io"
            git config user.signingkey BA5016990FD3D1F77858CFF7BA3B6486FE8AE132 ;;
        "personal")
            git config --unset user.email
            git config --unset user.signingkey ;;
    esac
}


# Update kernel function
function updk() {
    if ! cd "${HOME}/repos/pkgbuilds"; then
        display_error "PKGBUILD folder not found!"
        return
    fi

    if ! git fetch upstream packages/linux; then
        display_error "Error fetching upstream!"
        return
    fi

    if ! git ml --no-edit upstream/packages/linux; then
        display_error "Error updating from upstream!"
        return
    fi

    git push

    git cl

    cd trunk || return

    mkpkg
}


# Function to incrementally patch a kernel with stable
function stable-patch() {(
    CURRENT_VERSION=$(kver)
    TARGET_PATCH_LEVEL=$((${CURRENT_VERSION##*.} + 1))

    URL=https://cdn.kernel.org/pub/linux/kernel/v4.x/incr/patch-"${CURRENT_VERSION}"-"${TARGET_PATCH_LEVEL}".xz

    curl "${URL}" | xz -cd | git ap "${@}"

    echo
    echo
    echo "git ac -m \"treewide: Linux ${CURRENT_VERSION%.*}.${TARGET_PATCH_LEVEL}

source kernel.org
${URL}\""
    echo
    echo
)}


function test-pulls() {
    local BRANCH

    git fetch origin

    case "${PWD}" in
        *"sony"*)
            BRANCH=aosp/LA.UM.6.4.r1
            # Checkout a clean tree
            git ch "${BRANCH}"
            git push nathanchance HEAD:"${BRANCH}"
            git rh origin/"${BRANCH}"
            git bd testing &>/dev/null
            git ch -b testing
            if [[ ${#} -gt 0 ]]; then
                for NUMBER in "${@}"; do
                    git pll --no-edit origin pull/"${NUMBER}"/head
                done
            fi

            # Get Wi-Fi module
            qcacld -i
            git subtree pull -m "Merge pull request #11 from nathanchance/clang

$(signoff)" --prefix=drivers/staging/wlan-qc/qcacld-3.0 qcacld-3.0 refs/pull/11/head

            # Run all builds
            for DEFCONFIG in arch/arm64/configs/aosp_*; do
                build-kernel -d "$(basename "${DEFCONFIG}")" -w -Werror -c -ct aosp-clang/clang-r328903 -r
                build-kernel -d "$(basename "${DEFCONFIG}")" -w -Werror -c -ct aosp-clang/clang-4691093 -r
                build-kernel -d "$(basename "${DEFCONFIG}")" -w -Werror -gt btg-linaro-gcc-7.3.1-arm64 -r
                build-kernel -d "$(basename "${DEFCONFIG}")" -w -Werror -r
            done ;;
    esac
}


# Update/init qcacld-3.0 tree
function qcacld() {
    local REPO REPOS TAG URL

    REPOS=( "fw-api" "qcacld-3.0" "qca-wifi-host-cmn" )

    while [[ ${#} -ge 1 ]]; do
        case ${1} in
            "-i"|"--init") INIT=true ;;
            "-t"|"--tag") shift; TAG=${1} ;;
            "-u"|"--update") UPDATE=true ;;
        esac
        shift
    done
    [[ -n ${INIT} && -n ${UPDATE} ]] && { display_error "Both init and update were specified!"; return; }
    [[ -z ${TAG} && ! ${PWD} =~ "sony" ]] && { display_error "No tag was specified!"; return; }

    case "${PWD}:$(make kernelversion)" in
        *"sony"*)
            TAG=aosp/LA.UM.6.4.r1
            URL=https://github.com/sonyxperiadev/vendor-qcom-opensource-wlan-
            SUBFOLDER=drivers/staging/wlan-qc ;;

        *:"4.4"*|*:"4.9"*)
            URL=https://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/wlan/
            SUBFOLDER=drivers/staging ;;
    esac

    for REPO in "${REPOS[@]}"; do
        echo "${REPO}"
        if ! git ls-remote --exit-code "${REPO}" &>/dev/null; then
            git remote add "${REPO}" "${URL}${REPO}"
        fi
        git fetch "${REPO}" "${TAG}"
        if [[ -n ${INIT} ]]; then
            if [[ "${PWD}" =~ "sony" ]]; then
                git rm "${SUBFOLDER}/${REPO}"
                git ac -m "staging: ${REPO}: Remove submodule reference"
            fi

            git m --allow-unrelated-histories -s ours --no-commit FETCH_HEAD
            git read-tree --prefix="${SUBFOLDER}/${REPO}" -u FETCH_HEAD
            git c --no-edit -m "staging: ${REPO}: Checkout at ${TAG}"
        elif [[ -n ${UPDATE} ]]; then
            git m --no-edit -m "staging: ${REPO}: Merge tag '${TAG}' into $(git cb)" \
                  -X subtree="${SUBFOLDER}/${REPO}" FETCH_HEAD
        fi
    done
}


# build-tools-gcc wrapper
function btg() {(
    [[ "${*}" =~ "-t" || "${*}" =~ "--telegram" ]] && TG=true && TG_MSG_FILE=/tmp/tg-msg.3
    cd "${HOME}/gcc-build" || return
    git pull

    for ITEM in arm64:aarch64-linux-gnu arm:arm-linux-gnueabi; do
        ARCH=${ITEM%:*}
        TARGET=${ITEM#*:}

        for GCC in Linaro:7.3.1 GNU:8.1.1; do
            SOURCE=${GCC%:*}
            VERSION=${GCC#*:}
            START=$(date +"%s")
            ./build -a "${ARCH}" -s "${SOURCE,,}" -v "${VERSION:0:1}" --full-src
            TIME_ELAPSED=$(format_time "${START}" "$(date +"%s")")
            if [[ -d ${TARGET} ]]; then
                SOURCE_STRING=${SOURCE}
                [[ ${SOURCE} = "GNU" ]] && unset SOURCE || SOURCE="${SOURCE,,}-"
                FOLDER=${HOME}/toolchains/btg-${SOURCE}gcc-${VERSION}-${ARCH}
                rm -rf "${FOLDER}"
                mv "${TARGET}" "${FOLDER}"
                if [[ -n ${TG} ]]; then
                    {
                        echo "\`\`\`"
                        echo "${SOURCE_STRING} GCC ${VERSION} for ${ARCH} build successfully!"
                        echo
                        echo "Time elapsed: ${TIME_ELAPSED,,}"
                        echo
                        echo "Installation folder: ${FOLDER}"
                        echo
                        echo "Version: $("${FOLDER}/bin/${TARGET}-gcc" --version | head -1)"
                        echo "\`\`\`"
                    } > "${TG_MSG_FILE}"
                    notify "$(cat ${TG_MSG_FILE})"
                fi
            else
                if [[ -n ${TG} ]]; then
                    {
                        echo "\`\`\`"
                        echo "Error while building ${SOURCE} GCC ${VERSION} for ${ARCH}!"
                        echo
                        echo "Time elapsed: ${TIME_ELAPSED,,}"
                        echo "\`\`\`"
                    } > "${TG_MSG_FILE}"
                    notify "$(cat ${TG_MSG_FILE})"
                fi
            fi
        done
    done
)}


# Update all toolchains
function updtc() {
    local BINARIES

    # Clang 7.x
    build-clang -t
    # Clang 6.x
    build-clang -t -s
    # GCC 8.1.1 and GCC 7.3.1
    btg -t

    clear

    BINARIES=( "${HOME}/toolchains/flash-clang-7.x/bin/clang"
               "${HOME}/toolchains/flash-clang-6.x/bin/clang"
               "${HOME}/toolchains/btg-linaro-gcc-7.3.1-arm64/bin/aarch64-linux-gnu-ld"
               "${HOME}/toolchains/btg-linaro-gcc-7.3.1-arm/bin/arm-linux-gnueabi-ld" )

    for BINARY in "${BINARIES[@]}"; do
        ${BINARY} --version | head -1
        echo
    done
}


# Build all Flash Kernel builds a certain amount of times
function fkba() {(
    for DEVICE in marlin op6 wahoo; do
        rm -f "${LOG}"
        cd "${KERNEL_FOLDER}/flash/${DEVICE}" || { warn "${DEVICE} folder does not exist, skipping!"; continue; }
        [[ ${1} = "-n" || ${1} = "--number" ]] && { shift; NUM=${1}; }
        [[ -z ${NUM} ]] && NUM=1
        # SC2119: Use dib "$@" if function's $1 should mean script's $1.
        # shellcheck disable=SC2119
        for i in $(seq 1 ${NUM}); do dib; done
        notify "${DEVICE} results: $(deldog "${LOG}")"
    done
)}
