#!/usr/bin/env bash
#
# Utility and terminal setup functions for my Raspberry Pi
#
# Copyright (C) 2018 Nathan Chancellor
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>


# Raspberry Pi specific aliases
function raspberrypi_aliases() {
    # Kernel alias
    alias knl='cd ${HOME}/Documents/Kernel'

    # Build kernel alias
    alias pk='pi-kernel -b -i'

    # Git aliases since Raspbian doesn't have git 2.16.0+
    git config --global alias.m 'merge --gpg-sign'
    git config --global alias.ml 'merge --gpg-sign --log=500'
    git config --global alias.pl 'pull --gpg-sign'
    git config --global alias.pll 'pull --gpg-sign --log=500'
}


# Raspberry Pi setup (currently a no-op)
function raspberrypi_setup() { return; }


# Neofetch alias
function nf() {
    echo
    echo
    neofetch "$@"
}


# Update alias
function upd() {
    sudo apt-get update
    sudo apt-get upgrade
}
