#!/usr/bin/env bash
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2018 Nathan Chancellor
#
# Utility and terminal setup functions for my Raspberry Pi


# Raspberry Pi specific aliases
function raspberrypi_aliases() {
    # Kernel alias
    alias knl='cd ${HOME}/Documents/Kernel'

    # Build kernel alias
    alias pk='pi-kernel'

    # Scripts folder alias
    alias spt='cd ${HOME}/Documents/scripts'

    # Git aliases since Raspbian doesn't have git 2.16.0+
    git config --global alias.m 'merge --gpg-sign'
    git config --global alias.ml 'merge --gpg-sign --log=500'
    git config --global alias.pl 'pull --gpg-sign'
    git config --global alias.pll 'pull --gpg-sign --log=500'
}


# Raspberry Pi setup (currently a no-op)
function raspberrypi_setup() { return; }


# Neofetch alias
function nf() {
    echo
    echo
    neofetch "$@"
}


# Update alias
function upd() {
    sudo apt-get update
    sudo apt-get upgrade
}


# Update kernel function
function plk() {
    git f upstream rpi-4.14.y
    git ml --no-edit upstream rpi-4.14.y
}
