#!/usr/bin/env bash

PATCHES_FOLDER=$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)
git ra
git ap "${PATCHES_FOLDER}/f_midi.c.diff"
git ap "${PATCHES_FOLDER}/gadget.h.diff"
git ap "${PATCHES_FOLDER}/task_mmu.c.diff-tissot"
git ch v3.18.103 -- drivers/media/v4l2-core/v4l2-compat-ioctl32.c
git ap "${PATCHES_FOLDER}/v4l2-compat-ioctl32.c.diff"
git aa
git fm
