FROM docker.io/archlinux:base-devel

COPY setup-env.sh /
RUN bash /setup-env.sh && rm /setup-env.sh

USER build
WORKDIR /home/build
COPY --chown=build:build build-install-aur-packages.fish build-install-aur-packages.fish
COPY --chown=build:build cvise cvise/
RUN fish build-install-aur-packages.fish

USER root
RUN userdel -f -r build

CMD ["/usr/bin/fish", "-l"]
