[Content]
Autologin=yes
Bootable=true
RootPassword=hashed:$6$nCdbWlGRFR9lwsKq$AtkroVPPPjzF030V.6MBjSsC0F86xUfLRByXqoIablxmuJga8gGsLJ16BPM4wvJPfK0nDIZVoWm8dLRSq3RqT0
RootShell=/usr/bin/fish
Ssh=auto
Timezone=UTC

[Output]
Format=disk
Output=disk.img
OutputDirectory=/var/lib/machines/%i
