CL_PFX_BLD="\033[01;33m"
CL_INS_BLD="\033[01;36m"
CL_RED_BLD="\033[01;31m"
CL_GRN_BLD="\033[01;32m"
CL_YLW_BLD="\033[01;33m"
CL_BLU_BLD="\033[01;34m"
CL_MAG_BLD="\033[01;35m"
CL_CYN_BLD="\033[01;36m"
CL_PFX="\033[33m"
CL_INS="\033[36m"
CL_RED="\033[31m"
CL_GRN="\033[32m"
CL_YLW="\033[33m"
CL_BLU="\033[34m"
CL_MAG="\033[35m"
CL_CYN="\033[36m"
CL_RST="\033[0m"

test:
	@echo ""
	@echo -e ${CL_PFX_BLD}"This line is a test of the color CL_PFX_BLD"${CL_RST}
	@echo -e ${CL_PFX}"This line is a test of the color CL_PFX"${CL_RST}
	@echo ""
	@echo -e ${CL_INS_BLD}"This line is a test of the color CL_INS_BLD"${CL_RST}
	@echo -e ${CL_INS}"This line is a test of the color CL_INS"${CL_RST}
	@echo ""
	@echo -e ${CL_RED_BLD}"This line is a test of the color CL_RED_BLD"${CL_RST}
	@echo -e ${CL_RED}"This line is a test of the color CL_RED"${CL_RST}
	@echo ""
	@echo -e ${CL_GRN_BLD}"This line is a test of the color CL_GRN_BLD"${CL_RST}
	@echo -e ${CL_GRN}"This line is a test of the color CL_GRN"${CL_RST}
	@echo ""
	@echo -e ${CL_YLW_BLD}"This line is a test of the color CL_YLW_BLD"${CL_RST}
	@echo -e ${CL_YLW}"This line is a test of the color CL_YLW"${CL_RST}
	@echo ""
	@echo -e ${CL_BLU_BLD}"This line is a test of the color CL_BLU_BLD"${CL_RST}
	@echo -e ${CL_BLU}"This line is a test of the color CL_BLU"${CL_RST}
	@echo ""
	@echo -e ${CL_MAG_BLD}"This line is a test of the color CL_MAG_BLD"${CL_RST}
	@echo -e ${CL_MAG}"This line is a test of the color CL_MAG"${CL_RST}
	@echo ""
	@echo -e ${CL_CYN_BLD}"This line is a test of the color CL_CYN_BLD"${CL_RST}
	@echo -e ${CL_CYN}"This line is a test of the color CL_CYN"${CL_RST}
	@echo ""
