[Content]
Packages=
        # b4
        git-filter-repo

        # boot-qemu.py
        lsof

        # development
        ccache
        hyperfine

        # kernel / tuxmake
        bc
        bison
        cpio
        flex
        openssl
        rsync
        socat
        sparse

        # LLVM/clang + build-llvm.py
        cmake
