#!/usr/bin/env bash
# shellcheck disable=SC1091
# SPDX-License-Identifier: MIT
# Copyright (C) 2021-2022 Nathan Chancellor

bash_root=$(dirname "$0")

# Add common functions
source "$bash_root"/common || exit
source "$bash_root"/common_deb || exit

# Source os-release file for version variables
source /usr/lib/os-release || exit

function reality_check() {
    assert_root

    # shellcheck disable=SC2154
    if $pi; then
        : "${root_pass:?}" "${user_pass:?}"
    fi

    # This setup script only supports Debian 11
    case ${VERSION_CODENAME:?} in
        bullseye) ;;
        *)
            print_error "This script requires Debian 11"
            exit 1
            ;;
    esac
}

function install_initial_packages() {
    apt update -qq || exit
    apt install -y --no-install-recommends \
        apt-transport-https \
        ca-certificates \
        curl \
        gnupg || exit
}

function setup_fish_repo() {
    curl -fLSs https://download.opensuse.org/repositories/shells:fish:release:3/Debian_"${VERSION_ID:?}"/Release.key | gpg --dearmor | dd of=/etc/apt/trusted.gpg.d/shells_fish_release_3.gpg || exit
    echo "deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_$VERSION_ID/ /" | tee /etc/apt/sources.list.d/shells:fish:release:3.list || exit
}

function distro_packages() {
    $pi || return 0

    curl -fLSs https://pkgs.tailscale.com/stable/raspbian/bullseye.noarmor.gpg | dd of=/usr/share/keyrings/tailscale-archive-keyring.gpg || exit
    curl -fLSs https://pkgs.tailscale.com/stable/raspbian/bullseye.tailscale-keyring.list | tee /etc/apt/sources.list.d/tailscale.list || exit

    packages+=(
        qemu-system-arm # for /dev/kvm
        tailscale
    )
}

function pi_setup() {
    $pi || return 0

    # Add user account to kvm group for /dev/kvm access
    # shellcheck disable=SC2154
    usermod -aG kvm "$user_name"

    # Expand the rootfs to its full capacity
    raspi-config --expand-rootfs

    # Turn on the serial console by default
    raspi-config nonint do_serial 0

    # Update the pi account's password
    # shellcheck disable=SC2154
    echo "$user_name:$user_pass" | chpasswd

    # If the Pi has an external hard drive attached to it, add it to the fstab
    if [[ -b /dev/sda1 ]]; then
        mnt_point=/mnt/ssd
        mkdir -p "$mnt_point"
        chown -R "$user_name:$user_name" "$mnt_point"
        grep -q "$mnt_point" /etc/fstab || printf "PARTUUID=%s\t%s\text4\tdefaults,noatime\t0\t1\n" "$(blkid -o value -s PARTUUID /dev/sda1)" "$mnt_point" | tee -a /etc/fstab
    fi
}

parse_parameters "$@"
set_global_variables
reality_check
set_apt_variables
install_initial_packages
setup_fish_repo
setup_gh_repo
install_packages
chsh_fish
setup_doas
setup_locales
clone_env
podman_setup
pi_setup
set_date_time
setup_initial_fish_config
