#!/usr/bin/env bash
# shellcheck disable=SC1091
# SPDX-License-Identifier: MIT
# Copyright (C) 2022 Nathan Chancellor

bash_root=$(dirname "$0")

# Add common functions
source "$bash_root"/common || exit

# Source os-release file for version variables
source /usr/lib/os-release || exit

function reality_check() {
    assert_root

    # This setup script only supports Rocky 8.5
    case $VERSION_ID in
        8.5) ;;
        *)
            print_error "Rocky $VERSION_ID is not tested with this script, add support for it if it works."
            exit 1
            ;;
    esac
}

function install_initial_packages() {
    dnf update -y || exit
    dnf install -y dnf-plugins-core epel-release || exit
}

function setup_fish_repo() {
    dnf config-manager --add-repo https://download.opensuse.org/repositories/shells:fish:release:3/CentOS_8/shells:fish:release:3.repo || exit
}

function setup_gh_repo() {
    dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo || exit
}

function install_packages() {
    packages=(
        # administration
        mosh
        util-linux-user

        # email
        cyrus-sasl-plain
        mutt

        # env
        curl
        fish
        jq
        neofetch
        openssh
        stow
        tmux
        vim

        # git
        gh
        git{,-email}

        # podman (already installed but EPEL has a newer version)
        podman
    )

    dnf install -y "${packages[@]}" || exit

    # Reinstall shadow-utils to properly set capabilities
    # https://github.com/containers/podman/issues/2788
    dnf reinstall -y shadow-utils || exit
}

set_global_variables
reality_check
install_initial_packages
setup_fish_repo
setup_gh_repo
install_packages
chsh_fish
clone_env
setup_initial_fish_config
