#!/usr/bin/env bash
# shellcheck disable=SC1091
# SPDX-License-Identifier: MIT
# Copyright (C) 2021-2022 Nathan Chancellor

bash_root=$(realpath "$(dirname "$0")")
dpkg_arch=$(dpkg --print-architecture)

# Add common functions
source "$bash_root"/common || exit

# Source os-release file for version variables
source /usr/lib/os-release || exit

function reality_check() {
    assert_root

    # This setup script only supports Ubuntu 20.04 and 22.04
    case ${VERSION_CODENAME:?} in
        focal) ;;
        jammy) : "${root_pass:?}" ;; # for sudo removal
        *)
            print_error "This script requires Ubuntu 20.04 or 22.04"
            exit 1
            ;;
    esac
}

function set_apt_variables() {
    export APT_LISTCHANGES_FRONTEND=none
    export DEBIAN_FRONTEND=noninteractive
    export NEEDRESTART_SUSPEND=true
}

function install_initial_packages() {
    apt update -qq || exit
    apt install -y --no-install-recommends \
        apt-transport-https \
        ca-certificates \
        curl \
        gnupg || exit
}

function setup_docker_repo() {
    local docker_gpg_key=/etc/apt/trusted.gpg.d/docker.gpg

    curl -fLSs https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor | dd of=$docker_gpg_key
    echo "deb [arch=$dpkg_arch signed-by=$docker_gpg_key] https://download.docker.com/linux/ubuntu $VERSION_CODENAME stable" | tee /etc/apt/sources.list.d/docker.list || exit
}

function setup_fish_repo() {
    apt-add-repository -y ppa:fish-shell/release-3 || exit
}

function setup_gh_repo() {
    local gh_gpg_key=/etc/apt/trusted.gpg.d/githubcli-archive-keyring.gpg

    curl -fLSs https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=$gh_gpg_key || exit
    echo "deb [arch=$dpkg_arch signed-by=$gh_gpg_key] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list || exit
}

function setup_git_repo() {
    apt-add-repository -y ppa:git-core/ppa || exit
}

function install_packages() {
    packages=(
        # arc
        php{,-curl}

        # b4
        python3{,-{dkim,requests}}

        # doas
        libpam0g

        # Docker
        containerd.io
        docker-ce
        docker-ce-cli
        docker-compose-plugin

        # Downloading/extracting utilities
        bzip2
        ca-certificates
        curl
        unzip
        zip
        zstd

        # email
        mutt

        # env
        fish
        fzf
        jq
        neofetch
        python3-pip
        ripgrep
        stow
        tmux
        vim

        # git
        gh
        git
        git-email
        libauthen-sasl-perl
        libemail-valid-perl
        libio-socket-ssl-perl
        libnet-smtp-ssl-perl

        # Miscellaneous
        file
        locales

        # Remote work
        mosh
        ssh

        # repo
        python-is-python3
    )

    # Install libvirt and needed packages on Equinix Metal servers. Otherwise,
    # just install QEMU to get /dev/kvm setup properly.
    # shellcheck disable=SC2154
    if $equinix; then
        packages+=(
            dnsmasq
            libvirt-daemon-system
            qemu-utils
            virt-manager
        )
        case $dpkg_arch in
            amd64)
                packages+=(
                    ovmf
                    qemu-system-x86
                )
                ;;
            arm64)
                packages+=(
                    qemu-efi-aarch64
                    qemu-system-arm
                )
                ;;
        esac
    else
        case $dpkg_arch in
            amd64) packages+=(qemu-system-x86) ;;
            arm64) packages+=(qemu-system-arm) ;;
        esac
    fi

    apt_args=(
        -o Dpkg::Options::='--force-confdef'
        -o Dpkg::Options::='--force-confold'
        -y
    )

    apt update -qq || exit
    apt upgrade "${apt_args[@]}" || exit
    apt install \
        --no-install-recommends \
        "${apt_args[@]}" \
        "${packages[@]}" || exit
}

function setup_doas() {
    work_dir=$(mktemp -d)

    doas_version=6.8.2-1$([[ $dpkg_arch = "amd64" ]] && echo +b1)
    doas_deb="$work_dir"/opendoas_"$doas_version"_"$dpkg_arch".deb

    glibc_version=$(get_glibc_version)
    if (( glibc_version < 233000 )); then
        prebuilt_doas_deb="${bash_root%/*}"/bin/packages/"${doas_deb##*/}"
        cp -v "$prebuilt_doas_deb" "$doas_deb" || exit
    else
        curl -LSso "$doas_deb" http://http.us.debian.org/debian/pool/main/o/opendoas/"${doas_deb##*/}" || exit
    fi
    dpkg -i "$doas_deb" || exit

    cat <<EOF >/etc/doas.conf
# Allow me to be root for 5 minutes at a time
permit persist ${user_name:?} as root
# Do not require root to put in a password (makes no sense)
permit nopass root
EOF

    # Add a root password if requested so that there is no warning about removing sudo
    [[ -n $root_pass ]] && echo "root:$root_pass" | chpasswd

    # Uninstall sudo but create a symlink in case a program expects only sudo
    apt remove -y sudo
    setup_sudo_symlink

    rm -fr "$work_dir"
}

function setup_docker() {
    groupadd -f docker
    usermod -aG docker "$user_name" || exit

    # Pick up changes to daemon.json file
    systemctl restart {containerd,docker}.service || exit
}

function setup_libvirt() {
    is_installed virt-manager || return 0

    setup_libvirt_common
}

function setup_locales() {
    echo "locales locales/default_environment_locale select en_US.UTF-8" | debconf-set-selections
    echo "locales locales/locales_to_be_generated multiselect en_US.UTF-8 UTF-8" | debconf-set-selections
    rm -f /etc/locale.gen
    dpkg-reconfigure --frontend noninteractive locales
}

parse_parameters "$@"
set_global_variables
reality_check
set_apt_variables
install_initial_packages
setup_docker_repo
setup_fish_repo
setup_gh_repo
setup_git_repo
install_packages
chsh_fish
setup_doas
setup_docker
setup_libvirt
setup_locales
clone_env
set_date_time
setup_initial_fish_config
