#!/usr/bin/env bash
# shellcheck disable=SC1091
# SPDX-License-Identifier: MIT
# Copyright (C) 2021-2022 Nathan Chancellor

bash_root=$(dirname "$0")

# Add common functions
source "$bash_root"/common || exit
source "$bash_root"/common_deb || exit

# Source os-release file for version variables
source /usr/lib/os-release || exit

function reality_check() {
    assert_root

    # This setup script only supports Ubuntu 20.04
    case $VERSION_ID in
        20.04) ;;
        *)
            print_error "Ubuntu $VERSION_ID is not tested with this script, add support for it if it works."
            exit 1
            ;;
    esac
}

function install_initial_packages() {
    apt update -qq || exit
    apt install -y --no-install-recommends \
        gnupg \
        software-properties-common || exit
}

function setup_fish_repo() {
    apt-add-repository -y ppa:fish-shell/release-3 || exit
}

function setup_git_repo() {
    apt-add-repository -y ppa:git-core/ppa || exit
}

function setup_podman_repo_ubuntu() {
    case $VERSION_ID in
        20.04)
            setup_podman_repo xUbuntu_"$VERSION_ID"
            ;;
    esac
}

parse_parameters "$@"
set_global_variables
reality_check
set_apt_variables
install_initial_packages
setup_fish_repo
setup_gh_repo
setup_git_repo
setup_podman_repo_ubuntu
install_packages
chsh_fish
setup_doas
setup_locales
clone_env
podman_setup
set_date_time
setup_initial_fish_config
