#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Shebang is purely for syntax highlighting and shellcheck auditing; script must be sourced to be useful
#
# Copyright (C) 2019-2021 Nathan Chancellor
#
# Generic workstation environment setup script (usually for something like Vultr or Packet)

function rbld_usr() { (
    source "${SCRIPTS_FOLDER:?}"/env/stubs/updbin || die "Cannot source updbin"
    rm -rf "${HOME:?}"/usr
    updbin || die "updbin failed"
    iandroidtools || die "iandroidtools failed"
); }

function generic_setup() { true; }
# vi: filetype=zsh
