#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
#
# Shebang is purely for syntax highlighting and shellcheck auditing; script must be sourced to be useful
#
# Copyright (C) 2019-2021 Nathan Chancellor
#
# Generic workstation environment setup script (usually for something like Vultr or Packet)

function rbld_usr() { (
    source "${SCRIPTS_FOLDER:?}"/env/stubs/updbin || die "Cannot source updbin"

    # Clean up PREFIX
    RBLD_USR_PREFIX=${PREFIX:-${USR_FOLDER:?}}
    RBLD_USR_STOW=${RBLD_USR_PREFIX}/stow
    if [[ -d ${RBLD_USR_STOW} ]]; then (
        header "Cleaning up stow directory"
        cd "${RBLD_USR_STOW}" || exit ${?}
        for PACKAGE in *-latest git prebuilts scripts; do [[ -d ${PACKAGE} ]] && stow -D -v "${PACKAGE}"; done
    ); fi
    rm -rf "${RBLD_USR_PREFIX:?}"/{bin,doc,include,lib,libexec,share}
    mkdir -p "${RBLD_USR_STOW}"

    updbin || die "updbin failed"
    iandroidtools || die "iandroidtools failed"

    # Standalone kernel development scripts
    SCRIPTS_BIN=${RBLD_USR_STOW}/scripts/bin
    mkdir -p "${SCRIPTS_BIN}"
    for SCRIPT in "${SCRIPTS_FOLDER}"/kernel/*.sh; do
        ln -fsv "${SCRIPT}" "${SCRIPTS_BIN}"/"${SCRIPT##*/}"
    done
    stow -d "${RBLD_USR_STOW}" -v scripts
); }

function generic_setup() { true; }
# vi: filetype=zsh
