#!/bin/bash

function partition_and_create_user() {(
    # Function must be run as root
    [[ $(id -u) -ne 0 ]] && { echo -n "\033[01;31m\nThis script must be run as root.\n\033[0m"; exit 1; }

    # Drive to use must be provided as argument of script
    while (( ${#} )); do
        case ${1} in
            -d|--drive) shift; DRIVE=${1} ;;
            -p|--password) shift; PASSWORD=${1} ;;
        esac
        shift
    done

    # Debug and error if a command fails
    set -eux

    # Password must be supplied
    : ${PASSWORD}

    # Update apt files
    apt update

    # Install necessary files
    if [[ -n ${DRIVE:-} ]]; then
        case ${DRIVE} in
            /dev/nvme*) PART=p1 ;;
            /dev/sd*) PART=1 ;;
        esac
        apt install -y --no-install-recommends parted

        # Partition and modify fstab
        parted -s "${DRIVE}" mklabel gpt mkpart primary ext4 '0%' '100%'
        sleep 15
        mkfs -t ext4 "${DRIVE}${PART}"
        echo "UUID=$(blkid -o value -s UUID "${DRIVE}${PART}") /home ext4 noatime 0 2" >> /etc/fstab
        mount -a
    fi

    # Setup user account
    apt install -y --no-install-recommends zsh
    useradd -m -G sudo -s /bin/zsh nathan
    echo "nathan:${PASSWORD}" | chpasswd
    cp -rv /root/.ssh /home/nathan
    chown -R nathan:nathan /home/nathan/.ssh
)}
