#!/bin/bash

function partition_drive() {(
    # Function must be run as root
    [[ $(id -u) -ne 0 ]] && { printf "\033[01;31m\nThis function must be run as root.\n\033[0m"; exit 1; }

    while (( ${#} )); do
        case ${1} in
            -d|--drive) shift; DRIVE=${1} ;;
            -f|--folder) shift; FOLDER=${1} ;;
            -u|--user) shift; USER=${1} ;;
        esac
        shift
    done

    set -eux

    : "${DRIVE}" "${FOLDER}" "${USER}"

    case ${DRIVE} in
        /dev/nvme*) PART=p1 ;;
        /dev/sd*) PART=1 ;;
    esac

    # Partition and modify fstab
    parted -s "${DRIVE}" mklabel gpt mkpart primary ext4 '0%' '100%'
    sleep 15
    mkfs -t ext4 "${DRIVE}${PART}"
    printf 'UUID=%s\t%s\text4\tnoatime\t0\t2\n' "$(blkid -o value -s UUID "${DRIVE}${PART}")" "${FOLDER}" | tee -a /etc/fstab
    sed -i '/^$/d' /etc/fstab
    [[ ${FOLDER} != /home ]] && mkdir -p "${FOLDER}"
    mount -a
    [[ ${FOLDER} != /home ]] && chown -R "${USER}:${USER}" "${FOLDER}"
)}

function partition_and_create_user() {(
    # Function must be run as root
    [[ $(id -u) -ne 0 ]] && { printf "\033[01;31m\nThis function must be run as root.\n\033[0m"; exit 1; }

    # Drive to use must be provided as argument of script
    while (( ${#} )); do
        case ${1} in
            -d|--drive) shift; DRIVE=${1} ;;
            -p|--password) shift; PASSWORD=${1} ;;
            -s|--shell) shift; SHELL_PATH=${1} ;;
            -u|--user) shift; USER=${1} ;;
        esac
        shift
    done

    # Debug and error if a command fails
    set -eux

    # User and password must be supplied
    : "${USER}" "${PASSWORD}"

    # Always turn on '--no-install-recommends'
    apt-config dump | grep -we Recommends -e Suggests | sed 's/1/0/g' | tee /etc/apt/apt.conf.d/999norecommend

    # Update the server
    apt update
    apt upgrade -y

    # Install tmux so that installation progress cannot be lost
    apt install -y tmux

    # Install necessary files
    if [[ -n ${DRIVE:-} ]]; then
        apt install -y parted
        partition_drive -d "${DRIVE}" -f /home -u "${USER}"
    fi

    # Setup user account
    apt install -y qemu-kvm
    USER_ADD_ARGS=( -m -G kvm,sudo )
    if [[ "${SHELL_PATH:-}" = "/bin/zsh" ]]; then
        apt install -y zsh
        USER_ADD_ARGS=( "${USER_ADD_ARGS[@]}" -s "${SHELL_PATH}" )
    fi
    useradd "${USER_ADD_ARGS[@]}" "${USER}"
    echo "${USER}:${PASSWORD}" | chpasswd
    cp -rv /root/.ssh /home/"${USER}"
    chown -R "${USER}:${USER}" /home/"${USER}"/.ssh
)}
