[Match]
Distribution=fedora

[Content]
Packages=
        # base
        iputils
        man
        openssh
        procps-ng

        # compression / decompression / extraction
        xz

        # env
        fish

        # locale
        glibc-langpack-en

        # nicer GNU utilities
        # retired, leaving around in case it comes back:
        # https://bugzilla.redhat.com/show_bug.cgi?id=2262203
        # eza
        fd-find

        # python
        python3
        python-unversioned-command

# Avoid systemd-firstboot prompt for root password (the user will have
# passwordless sudo anyways)
RootPassword=hashed:$y$j9T$eyJouRjyaAIzfpUIX1ToK1$kLouaq9LvZFG0wSzvJBCVFWLx.it6tcgJdYmOzgCq0D

[Distribution]
Release=rawhide
