[Match]
Distribution=fedora

[Content]
Packages=
        # base
        btop
        dnf
        iputils
        man
        openssh
        procps-ng

        # compression / decompression / extraction
        xz

        # env
        fish

        # locale
        glibc-langpack-en

        # nicer GNU utilities
        duf
        # retired, leaving around in case it comes back:
        # https://bugzilla.redhat.com/show_bug.cgi?id=2262203
        # eza
        fd-find

        # python
        python3
        python-unversioned-command

[Distribution]
Release=rawhide
