name: Debian development container image

on:
  push:
    paths:
      - .github/workflows/dev-debian.yml
      - podman/dev/debian/*
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:
    inputs:
      push_image:
        description: 'Push image to ghcr.io'
        required: false
        type: boolean

jobs:
  build_and_push:
    name: Build and push Debian container image
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      context: ./podman/dev/debian
      image: dev/debian
      platforms: linux/amd64,linux/arm64
      push: ${{ github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.push_image == 'true') }}
