name: Build binary container images

on:
  push:
    branches:
      - dev
      - main
    paths:
      - .github/workflows/docker-binary.yml
      - podman/lei/**
      - podman/makepkg/**
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch: null

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        binary: [lei, makepkg]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name == 'schedule' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set variables
        id: variables
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M')"

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./podman/${{ matrix.binary }}
          file: ./podman/${{ matrix.binary }}/Containerfile
          platforms: linux/amd64
          push: ${{ github.event_name == 'schedule' }}
          tags: |
            ghcr.io/nathanchance/${{ matrix.binary }}:${{ steps.variables.outputs.date }}
            ghcr.io/nathanchance/${{ matrix.binary }}:latest
