name: Build and push a container image to ghcr.io

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
      image:
        required: true
        type: string
      platforms:
        required: true
        type: string
      push:
        default: false
        required: false
        type: boolean

jobs:
  build_and_push_image:
    name: Build and push container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        if: ${{ inputs.push }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set variables
        id: variables
        run: |
          echo "date=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_OUTPUT

      - name: Build
        uses: docker/build-push-action@v3
        with:
          build-args: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          context: ${{ inputs.context }}
          file: ${{ inputs.context }}/Dockerfile
          platforms: ${{ inputs.platforms }}
          push: ${{ inputs.push }}
          tags: |
            ghcr.io/${{ github.actor }}/${{ inputs.image }}:${{ steps.variables.outputs.date }}
            ghcr.io/${{ github.actor }}/${{ inputs.image }}:latest
