name: Build compiler container images

on:
  push:
    paths:
      - .github/workflows/docker-compiler.yml
      - podman/compiler/**
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:
    inputs:
      push_images:
        description: 'Push images to ghcr.io'
        required: false
        type: boolean

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - base: ubuntu:xenial
            compiler: gcc-5
            platforms: linux/amd64,linux/arm64

          - base: ubuntu:focal
            compiler: llvm-11
            platforms: linux/amd64

          - base: ubuntu:focal
            compiler: llvm-12
            platforms: linux/amd64

          - base: ubuntu:jammy
            compiler: llvm-13
            platforms: linux/amd64,linux/arm64

          - base: ubuntu:jammy
            compiler: llvm-14
            platforms: linux/amd64,linux/arm64

          - base: ubuntu:jammy
            compiler: llvm-15
            platforms: linux/amd64,linux/arm64

          - base: ubuntu:jammy
            compiler: llvm-16
            platforms: linux/amd64,linux/arm64

          - base: ubuntu:jammy
            compiler: llvm-17
            platforms: linux/amd64,linux/arm64

          - base: ubuntu:jammy
            compiler: llvm-android
            platforms: linux/amd64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.push_images == 'true') }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set variables
        id: variables
        run: |
          echo "date=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_OUTPUT
          echo "folder=./podman/compiler" >> $GITHUB_OUTPUT

      - name: Build
        uses: docker/build-push-action@v3
        with:
          build-args: |
            BASE=docker.io/${{ matrix.base }}
            COMPILER=${{ matrix.compiler }}
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          context: ${{ steps.variables.outputs.folder }}
          file: ${{ steps.variables.outputs.folder }}/Dockerfile
          platforms: ${{ matrix.platforms }}
          push: ${{ github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.push_images == 'true') }}
          tags: |
            ghcr.io/nathanchance/${{ matrix.compiler }}:${{ steps.variables.outputs.date }}
            ghcr.io/nathanchance/${{ matrix.compiler }}:latest
