# Run a bunch of lint checks to keep me honest
name: Linting
on:
  push:
    paths:
      - '**.fish'
      - '**.py'
      - '**.sh'
  pull_request:
    paths:
      - '**.fish'
      - '**.py'
      - '**.sh'
jobs:
  fish:
    uses: nathanchance/actions-workflows/.github/workflows/fish_format.yml@main
  python:
    strategy:
      fail-fast: false
      matrix:
        version: ['3.14', '3.13', '3.12', '3.11', '3.10']
    uses: nathanchance/actions-workflows/.github/workflows/python_lint.yml@main
    with:
      python_version: ${{ matrix.version }}
  shellcheck:
    uses: ClangBuiltLinux/actions-workflows/.github/workflows/shellcheck.yml@main
  shfmt:
    uses: ClangBuiltLinux/actions-workflows/.github/workflows/shfmt.yml@main
