# Run shellcheck and shfmt on all shell files in this repository
name: linting
on: [push, pull_request]
jobs:
  fish_indent:
    runs-on: ubuntu-latest
    name: 'fish_indent'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: fish_indent
        uses: ./ci
        with:
          check: 'fish_indent'
  shellcheck:
    runs-on: ubuntu-latest
    name: 'shellcheck'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: shellcheck
        uses: ./ci
        with:
          check: 'shellcheck'
  shfmt:
    runs-on: ubuntu-latest
    name: 'shfmt'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: shfmt
        uses: ./ci
        with:
          check: 'shfmt'
