# Run shellcheck and shfmt on all shell files in this repository
name: Linting
on: [push, pull_request]
jobs:
  fish_indent:
    runs-on: ubuntu-latest
    name: 'fish_indent'
    steps:
      - uses: actions/checkout@v3
      - uses: fish-actions/install-fish@v1
      - uses: fish-actions/format-check@v1
  shellcheck:
    uses: ClangBuiltLinux/actions-workflows/.github/workflows/shellcheck.yml@main
  shfmt:
    uses: ClangBuiltLinux/actions-workflows/.github/workflows/shfmt.yml@main
