# Run shellcheck and shfmt on all shell files in this repository
name: Linting
on: [push, pull_request]
jobs:
  fish_format:
    uses: nathanchance/actions-workflows/.github/workflows/fish_format.yml@main
  shellcheck:
    uses: ClangBuiltLinux/actions-workflows/.github/workflows/shellcheck.yml@main
  shfmt:
    uses: ClangBuiltLinux/actions-workflows/.github/workflows/shfmt.yml@main
  yapf:
    name: 'yapf'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: yapf
        uses: AlexanderMelde/yapf-action@v1.0
        with:
          args: --exclude '**/skeletons/**'
