# Run shellcheck and shfmt on all shell files in this repository
name: Linting
on: [push, pull_request]
jobs:
  fish_indent:
    name: 'fish_indent'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fish-actions/install-fish@v1
      - uses: fish-actions/format-check@v1
  shellcheck:
    uses: ClangBuiltLinux/actions-workflows/.github/workflows/shellcheck.yml@main
  shfmt:
    uses: ClangBuiltLinux/actions-workflows/.github/workflows/shfmt.yml@main
  yapf:
    name: 'yapf'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: yapf
        uses: AlexanderMelde/yapf-action@v1.0
        with:
          args: --exclude '**/skeletons/**'
